### ISSUE TITLE
Lossless?

### ISSUE THREAD

**Issue by lencioni** [RazrFalcon/svgcleaner#102]
I noticed the readme says:

> svgcleaner is strictly lossless. There are no destructive cleaning options.

It seems to me that the precision options are not lossless, so I'm wondering if this is still accurate?

**Comment by RazrFalcon** [comment]
Yes. Readme is a bit outdated. Better to say that it's lossless by default.

**Comment by lencioni** [comment]
Cool, I'll open a PR!
