### ISSUE TITLE
Error: Cleaned file is bigger than original.

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#106]
How can I force svgcleaner to save a file even it is bigger than before? (I need to debug, because I want to know which option breaks the file.)

**Comment by RazrFalcon** [comment]
`--allow-bigger-file`?

**Comment by JoKalliauer** [comment]
Thanks, sorry didn't read the first lines of

> $ svgcleaner.exe --help

**Comment by JoKalliauer** [comment]
@RazrFalcon For your Information:
I processed the file:
[https://commons.wikimedia.org/wiki/File:Georgia_regions_map2.svg](https://commons.wikimedia.org/wiki/File:Georgia_regions_map2.svg)
enabling: `--join-arcto-flags yes`
and the file was rendered correcly by brower/inkscape but not by libRSVG:
[https://de.wikipedia.beta.wmflabs.org/wiki/Datei:Georgia_regions_map2_buggy.svg](https://de.wikipedia.beta.wmflabs.org/wiki/Datei:Georgia_regions_map2_buggy.svg)

I think it might be a libRSVG-bug and not your mistake. (Honnestly I don't know what joining ArcTo flags means).

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.rst#join-arcto-flags

>Unsupported by: Inkscape <= 0.91 r13725, QtSvg <= 5.7, librsvg <= 2.40.13
