### ISSUE TITLE
Error: Conditional processing attributes is not supported.

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#107]
If i compress [https://commons.wikimedia.org/wiki/File:Germanwings_Flight_9525_flight_path_topographic_vector.svg](https://commons.wikimedia.org/wiki/File:Germanwings_Flight_9525_flight_path_topographic_vector.svg)
with:
> $ svgcleaner.exe Germanwings_Flight_9525_flight_path_topographic_vector.svg test.svg

I get an Error:
`Error: Conditional processing attributes is not supported.`

**Comment by RazrFalcon** [comment]
Yes. Such svg files is not supported.

**Comment by JoKalliauer** [comment]
So the language-switch is not supported.
I am repairing broken Files and make workarounds for libRSVG-bugs on Wikipedia: https://github.com/JoKalliauer/cleanupSVG
(Not as great tool as yours and much more then 10times slower)

My tool searches for svg-files in the current folder and uses different tools such as scour or yours and save the output as new svg and the old one will be renamed to a backup-file with a different fileextension, therfore the next tool can't find any svg-files. (I could rewrite my code.)

Therefore I have two questions:
1)is it (easily) possible to compress the part outside the language-switch (without cut&paste the <switch>[...]</switch> on my own)
2)If svgcleaner is not possible to handle the file, can I enforce svgcleaner to write "any" file (the unprocessed file)?

**Comment by RazrFalcon** [comment]
1. Currently - no. `switch` is the easy one, but there are stuff that will never be supported, like scripting and animations. It's too easy to mess up everything, so svgcleaner just skip this files completely for now.
2. `--copy-on-error`?

**Comment by JoKalliauer** [comment]
Thanks great. Shame on me, again didn't read
`$ svgcleaner.exe --help`
because I expected it is not implemented.

Your tool is great 👍 and the support also, and an awesome [documentation](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.rst).
I like the perception of (good &) free software and also this great support, for my dumb questions.

Therefore I would like to thank you with to financially support (just in the amount of a coffee or so) your open source project.

**Comment by RazrFalcon** [comment]
Thanks, but I don't have an online wallet. =)

**Comment by RazrFalcon** [comment]
Conditional processing depends on UA, so it can be done in the svgc.
