### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20 note: Run with `RUST_BACKTRACE=1` for a backtrace.

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#108]
If i process the file:
[https://commons.wikimedia.org/wiki/File:LageplanStrasse.svg](https://commons.wikimedia.org/wiki/File:LageplanStrasse.svg)
with
> $ svgcleaner.exe LageplanStrasse.svg hallo.svg

I get the error:
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.

with
> $ export RUST_BACKTRACE=1

I get the following error:
>thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
stack backtrace:
   0: &lt;unknown>
   1: &lt;unknown>
   2: &lt;unknown>
   3: &lt;unknown>
   4: &lt;unknown>
   5: &lt;unknown>
   6: &lt;unknown>
   7: &lt;unknown>
   8: &lt;unknown>
   9: &lt;unknown>
  10: BaseThreadInitThunk

I am Running Rust 1.22.1 (05e2e1c41 2017-11-22) on Windows 10 with Cygwin. (with CMD the error also occurs)

**Comment by RazrFalcon** [comment]
Yep. That's a bug.

The file contains such subpath `zh-205 204z`, which is incorrect, because subpath can start only with MoveTo. I should validate this. And now I just assume that path is valid.

**Comment by RazrFalcon** [comment]
Fixed by https://github.com/RazrFalcon/libsvgparser/commit/4e836108b196ff67c5d7d25dddefa03ef58a239e

I'm planing to release 0.9.2 soon, so this fix will be there.

**Comment by RazrFalcon** [comment]
It's actually the svgcleaner bug...
