### ISSUE TITLE
stroke-width="null"

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#109]
svgCleaner can't handle the file:
[https://commons.wikimedia.org/wiki/File:Great-plate-count-anomaly_Workaround.svg](https://commons.wikimedia.org/wiki/File:Great-plate-count-anomaly_Workaround.svg)
because of
> stroke-width="null"

it reports:
> Error: Invalid number at 5:116.

but the W3C-Validater says it is a valid file:
[https://validator.w3.org/check?uri=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilepath%2FGreat-plate-count-anomaly_Workaround.svg&ss=1](https://validator.w3.org/check?uri=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilepath%2FGreat-plate-count-anomaly_Workaround.svg&ss=1), just a warning because of the metadata.

I'm not shure if stroke-width="null" stands for the default: stroke-width="1" or for stroke-width="0"? Maybe it is not even allowed/defined the value "null" ?

**Comment by RazrFalcon** [comment]
I don't know how it passes the validator, but it's incorrect. 

https://www.w3.org/TR/SVG11/painting.html#StrokeWidthProperty

> Value: percentage | length | inherit

I don't know what should I do in such case.

**Comment by JoKalliauer** [comment]
I would ignore this.
In my [code](https://github.com/JoKalliauer/cleanupSVG/blob/master/svg2validsvg.sh) I will delete it:
> sed -i "s/ stroke-width=\"null\"//g" $i

The original code had many Errors:
[https://commons.wikimedia.org/wiki/File:Great-plate-count-anomaly.svg](https://commons.wikimedia.org/wiki/File:Great-plate-count-anomaly.svg)

I deleted everything what was reported by validator, therefore the file was valid according to the validator. now I will also delete `stroke-width="null"`, since is is the same mistake as the other errors like
- `stroke-linejoin="null"`
- `stroke-linecap="null"`

which were reported as incorrect.
