### ISSUE TITLE
apply-transform-to-paths seems to remove objects

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#111]
Processing
> $ svgcleaner.exe input.svg output.svg --indent 1 --allow-bigger-file --apply-transform-to-paths yes

for
[https://commons.wikimedia.org/wiki/File:History_of_the_Universe-zh-hant.svg](https://commons.wikimedia.org/wiki/File:History_of_the_Universe-zh-hant.svg)
does "remove" tree stars.

Because the file is quite big I tried a minimal working example:
[H.svg.TXT](https://github.com/RazrFalcon/svgcleaner/files/1564748/H.svg.TXT)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg viewBox="0 0 5500 4250" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <radialGradient id="a" cx="4965" cy="3101.6" gradientUnits="userSpaceOnUse" r="7.989">
  <stop offset="0" stop-color="#fff" stop-opacity=".807"/>
  <stop offset="1" stop-opacity="0"/>
 </radialGradient>
 <path d="m0 0h5500v4250h-5500z"/>
 <g fill="url(#a)">
  <path d="m4973 3101.6a7.9887 7.9887 0 1 1 -15.977 0 7.9887 7.9887 0 1 1 15.977 0z" transform="matrix(2 0 0 2 -4957 -3093.6)"/>
  <path d="m4973 3101.6a7.9887 7.9887 0 1 1 -15.977 0 7.9887 7.9887 0 1 1 15.977 0z" transform="matrix(2 0 0 2 -4823.1 -3661)"/>
  <path d="m4973 3101.6a7.9887 7.9887 0 1 1 -15.977 0 7.9887 7.9887 0 1 1 15.977 0z" transform="matrix(2.75 0 0 2.75 -8660.7 -6340.7)"/>
 </g>
</svg>
```

then the output was:
```svg
<svg viewBox="0 0 5500 4250" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <radialGradient id="a" cx="4965" cy="3101.6" gradientUnits="userSpaceOnUse" r="7.989">
  <stop offset="0" stop-color="#fff" stop-opacity=".807"/>
  <stop offset="1" stop-opacity="0"/>
 </radialGradient>
 <path d="m0 0h5500v4250h-5500z"/>
 <g fill="url(#a)">
  <path d="m4989 3109.6a15.9774 15.9774 0 1 1 -31.954 0 15.9774 15.9774 0 1 1 31.954 0z" stroke-width="2"/>
  <path d="m5122.9 2542.2a15.9774 15.9774 0 1 1 -31.954 0 15.9774 15.9774 0 1 1 31.954 0z" stroke-width="2"/>
  <path d="m5015.049999999999 2188.7a21.968925 21.968925 0 1 1 -43.936749999999 0 21.968925 21.968925 0 1 1 43.936749999999 0z" stroke-width="2.75"/>
 </g>
</svg>
```

The first file is rendered correctly in inkscape, chrome and firefox the second in none.

**Comment by RazrFalcon** [comment]
Strange... Will investigate this.

PS: Do you have a local copy of wiki's SVG images or you just cleaning random images?

**Comment by JoKalliauer** [comment]
I created only few SVGs on my own ([Gallery of my svgs](https://commons.wikimedia.org/wiki/User:JoKalliauer#Technical_vektor-drawings_(svg))). If created in Inscape there is normally no problem with them. Some are created with CAD-Programms (and imported in Inkscape as pdf) like [LageplanStrasse.svg](https://commons.wikimedia.org/wiki/File:LageplanStrasse.svg), they tend to be more buggy, see f.e. #108

On commons I try to correct following files:
- [Pictures_showing_a_librsvg_bug](https://commons.wikimedia.org/wiki/Category:Pictures_showing_a_librsvg_bug)
- [SVG_files_with_multiple_W3C-errors](https://commons.wikimedia.org/wiki/Category:SVG_files_with_multiple_W3C-errors)
- [Large_SVG_files](https://commons.wikimedia.org/wiki/Category:Large_SVG_files)

they often created by very different software, which have a "buggy" svg-export and uses functions which are not as common.
Inkscape-errors are generally very vell known, and therefore there is a big efford to correct them.

**Comment by RazrFalcon** [comment]
Yes, inkscape and rsvg errors is a big problem. That's why I'm developing [libresvg](https://github.com/RazrFalcon/libresvg).
