### ISSUE TITLE
definitions in <style> get deleted

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#112]
Prozessing the file [https://commons.wikimedia.org/wiki/File:Instrumental_Temperature_Record_GISS.svg](https://commons.wikimedia.org/wiki/File:Instrumental_Temperature_Record_GISS.svg)
even with disabling all options leads to a remove of the blue dots.

Here is a minimal working example:
[min.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1564991/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 480 384" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <style id="style4" type="text/css"><![CDATA[
   .tempMarker {
     fill: blue;
     stroke: blue;
   }
   .annualTemp {
     fill: none;
     stroke: #333;
     stroke-width: 0.5;
     stroke-linecap: butt;
     stroke-linejoin: bevel;
     marker: url(#tempMarker);
   }
 ]]></style>
 <marker id="tempMarker" markerHeight="4" markerWidth="4" refX="2" refY="2">
  <circle id="circle6" cx="2" cy="2" fill="#0000ff" r="1.5" stroke="#0000ff"/>
 </marker>
 <g class="annualTemp" fill="none" stroke="#333" stroke-linejoin="bevel" stroke-width=".5" transform="matrix(3 0 0 -3 -5565 222)">
  <path class="annualTemp" d="m1888 54h5 5"/>
  <path class="annualTemp" d="m1880-25 1 5 1-2 1-2 1-6h1l1 5 1-10 1 8 1 12 1-22 1 10 1-5 1 1 1-2 1 6 1 11 1 4 1-12 1 7 1 8 1-6 1-12 1-4 1-3 1 10 1 4 1-18 1 4 1-1 1 2h1l1-1 1 2 1 17 1 6 1-22 1-9 1 8 1 12 1 1 1 6 1-11 1 4 1-1 1 5 1 15 1-12 1 2 1-14 1 18 1 6 1-5 1-12 1 11 1-4 1 8 1 11 1 3 1-8 1 2 1 5 1-7 1 7 1 10 1-13 1-11 1 4 1-4 1-3 1-8 1 11 1 7 1 8 1-21h1l1-7 1 24 1 1 1-2 1-7 1 9 1-4 1 4 1-29 1 10 1 8 1 3 1-4 1 12 1-5 1-13 1 10 1 14 1-22 1 3 1-11 1 29 1-12 1 8 1 9 1 8 1-21 1 21 1-17 1-4 1 8 1 13 1 5 1-11 1 18 1-3 1-22 1 1 1 9 1 15 1-9 1 11 1 16 1-24 1 1 1 15 1 8 1-1 1-6 1 14 1-9 1 3 1-14 1 14"/>
 </g>
</svg>
```

and svgcleaner removes `<style>` and `class="annualTemp"` but it is still needed.

Also scour you need the option `--keep-unreferenced-defs`:
https://github.com/scour-project/scour/issues/155

**Comment by RazrFalcon** [comment]
The `style` element and `class` attributes are not removed. They are resolved. But there is some bug in the process.

**Comment by RazrFalcon** [comment]
It's actually a popular bug. Many applications doesn't support `marker` attribute inside the element, only in `style`.

From the SVG spec:
>The ‘marker’ property specifies the marker symbol that shall be used for all points on the sets the value for all vertices on the given ‘path’ element or basic shape. It is a short-hand for the three individual marker properties.

So svgcleaner is technically correct. To fix this I have to replace `marker` with `marker-start`, `marker-mid` and `marker-end`. It will obviously make file bigger which is undesirable.

I will think about what can be done here.

**Comment by JoKalliauer** [comment]
`marker` is according to W3C-Validator not supported in path therefore, I think you can close this bug.

Thanks you helped me to make an workaround for the picture:
[https://commons.wikimedia.org/wiki/File:Instrumental_Temperature_Record_GISS_Workaround.svg](https://commons.wikimedia.org/wiki/File:Instrumental_Temperature_Record_GISS_Workaround.svg)

**Comment by RazrFalcon** [comment]
>marker is according to W3C-Validator not supported in path

Why so?

https://www.w3.org/TR/SVG11/painting.html#MarkerProperty

>Applies to: ‘path’, ‘line’, ‘polyline’ and ‘polygon’ elements

**Comment by JoKalliauer** [comment]
Test following file:
[MinWorkExample.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1565068/MinWorkExample.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg version="1.1" viewBox="0 0 480 384" xmlns="http://www.w3.org/2000/svg">
 <path d="m99 60h30" marker="url(#a)" stroke="#333"/>
</svg>
```
in https://validator.w3.org/#validate_by_input
it reports an error:
`Line 4, Column 29: there is no attribute "marker"`

**Comment by JoKalliauer** [comment]
One example from:
https://www.w3.org/TR/SVG11/painting.html#MarkerProperty

```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="4in" height="2in" 
     viewBox="0 0 4000 2000" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
  <defs>
    <marker id="Triangle"
      viewBox="0 0 10 10" refX="0" refY="5" 
      markerUnits="strokeWidth"
      markerWidth="4" markerHeight="3"
      orient="auto">
      <path d="M 0 0 L 10 5 L 0 10 z" />
    </marker>
  </defs>
  <rect x="10" y="10" width="3980" height="1980"
       fill="none" stroke="blue" stroke-width="10" />
  <desc>Placing an arrowhead at the end of a path.
  </desc>
  <path d="M 1000 750 L 2000 750 L 2500 1250"
        fill="none" stroke="black" stroke-width="100" 
        marker-end="url(#Triangle)"  />
</svg>
```

It think marker is used in this way:
```svg
    <marker>
      <path/>
    </marker>
```

**Comment by RazrFalcon** [comment]
`marker` is a valid attribute according to the SVG spec. I don't why this validator doesn't like it.
