### ISSUE TITLE
stroke-dasharray : comma - space

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#113]
The librsvg-Render don't handle spaces in stoke-dasharray:
[https://phabricator.wikimedia.org/T32033](https://phabricator.wikimedia.org/T32033)
therefore I need commas instead of spaces. (at least if the input are commas the output should also be) Maybe an option `--renderer-workaround ` as in scour, or you can also always use commas, they need the same number of characters.

See also:
[https://commons.wikimedia.org/wiki/Librsvg_bugs#stroke-dasharray](https://commons.wikimedia.org/wiki/Librsvg_bugs#stroke-dasharray)

**Comment by RazrFalcon** [comment]
rsvg has a ton of bugs. Making workarounds for them is not my job. All I can do is to make an option to choose a separator for `list-of-numbers`/`list-of-lengths` data type.

**Comment by JoKalliauer** [comment]
I would say it is one of the most famous one, which is very easy to solve. And if I have a correct file, I don't want that it get messed up, you don't have to repair them, but you shouldn't produce Rendererrors .

[scour](https://github.com/scour-project/scour),  [svgo](https://github.com/svg/svgo) and Inkscape keep the inputformat.

**Comment by RazrFalcon** [comment]
Well, svgcleaner is correct according to the SVG spec. It's purely the rsvg problem.

**Comment by JoKalliauer** [comment]
Both specification are correct, but W3C uses commas on there website:
https://www.w3.org/TR/svg-strokes/#StrokeDashing

I'm not happy about it, but it is up on you if you want to change it.

**Comment by RazrFalcon** [comment]
There is nothing to change. ` ` is equal to `,` and to `, ` in the SVG. All I can do is to add an option to choose a specific format.

**Comment by JoKalliauer** [comment]
Thank you very much! :)

Is there a possibility to get the unreleased version?
(Sorry I'm not that familiar neither with Github nor compiling on my own, and I never heard [rust](https://www.rust-lang.org/de-DE/) before.)

[I'm using Cygwin (With `cargo 0.23.0 (61fa02415 2017-11-22)`), but if you could explain how it would work on Linux or Windows, I think I will manage on my own to get it run also in Cygwin.]

**Comment by RazrFalcon** [comment]
I think this should work:
```
cargo install --force --git https://github.com/RazrFalcon/svgcleaner --branch devel --bin svgcleaner
```

But it doesn't. Probably a cargo bug.

**Comment by RazrFalcon** [comment]
@JoKalliauer 

Seems like the working command is:
```
cargo install --force svgcleaner --git https://github.com/RazrFalcon/svgcleaner
```

**Comment by JoKalliauer** [comment]
@RazrFalcon : Thanks:

For me

```
cargo install --force --git https://github.com/RazrFalcon/svgcleaner --branch devel svgcleaner
```

worked
