### ISSUE TITLE
option keep flow text

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#115]
Is there an option to keep flow text?
https://www.w3.org/TR/2004/WD-SVG12-20041027/flow.html

I didn't find any option for it in 
>$ svgcleaner --help

**Comment by RazrFalcon** [comment]
`flowText` is not an SVG element, so `--remove-nonsvg-elements=no`.

**Comment by JoKalliauer** [comment]
Thank you very much.
It actually leaded in combination with `--apply-transform-to-paths yes` to a new error: #116
