### ISSUE TITLE
Refuses to save fiels with .temp extension

### ISSUE THREAD

**Issue by pornel** [RazrFalcon/svgcleaner#118]
The CLI interface requires output to have .svg extension. I suppose it's to stop users for expecting .png or svg.gz, but it gets in the way of automated scripts that don't care about extensions.

Could you change the error to a warning or add a `--force` flag?

**Comment by RazrFalcon** [comment]
Can't you rename it afterwards?

It's easy to implement, but I don't think than it's a good idea.

**Comment by pornel** [comment]
I've worked around it by using stdout output.
