### ISSUE TITLE
Error: unsupported CSS

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#119]
Processing the file: [https://commons.wikimedia.org/wiki/File:Tsumeshogi-classic.svg](https://commons.wikimedia.org/wiki/File:Tsumeshogi-classic.svg) with
> $ svgcleaner [Tsumeshogi-classic.svg](https://upload.wikimedia.org/wikipedia/commons/7/73/Tsumeshogi-classic.svg) output.svg

leads to an error:
`Error: unsupported CSS`

I think the problem is `g.promoted>text{fill:red}`:
```
<style id="style2" type="text/css"><![CDATA[text{fill:#000;stroke:none;font-family:sans;text-anchor:middle}g.promoted>text{fill:red}]]></style>
```

minimal working example:
[min.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1587455/min.svg.txt)

```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg id="svg94" width="226" height="201" version="1.1" viewBox="-.5 -10 113 100.5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <style id="style2" type="text/css"><![CDATA[text{fill:#000;stroke:none;font-family:sans;text-anchor:middle}g.promoted>text{fill:red}]]></style>
 <defs id="defs8">
  <g id="bishop-plus-char" class="piece promoted">
   <text id="text5" x="5" y="8" font-size="8">馬</text>
  </g>
  <g id="pawn-plus-char" class="piece promoted">
   <text id="text9" x="5" y="8" font-size="8">个</text>
  </g>
 </defs>
 <use id="use59" x="40" y="20" xlink:href="#pawn-plus-char"/>
 <use id="use61" x="70" y="40" xlink:href="#bishop-plus-char"/>
</svg>

```

Is there an option to ignore errors? (And repair the file by hand afterwards.)
I understand if you don't want to allow ignoring errors, because the errormessages make sence.

**Comment by RazrFalcon** [comment]
Yes, CSS support is quite minimal. If you skip this error all you get is a broken file. That's it. I don't see a point in this.

You should "fix" the CSS before cleaning.
