### ISSUE TITLE
stroke="currentColor"

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#120]
Processiong [https://commons.wikimedia.org/wiki/File:O_Canada_Lilypond.svg](https://commons.wikimedia.org/wiki/File:O_Canada_Lilypond.svg) with:
>$svgcleaner [O_Canada_Lilypond.svg](https://commons.wikimedia.org/wiki/File:O_Canada_Lilypond.svg) output.svg

leads to white instead of black lines because it removes:
`stroke="currentColor"`

minimal working example:
[min.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1587854/min.svg.txt)

```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg height="157mm" viewBox="-2.185 0 110.6 89.34" width="194.4mm" xmlns="http://www.w3.org/2000/svg">
 <g stroke="currentColor">
  <path d="m.05 0h99.48" transform="translate(8.536 16.11)"/>
  <path d="m.05 0h99.48" transform="translate(8.536 15.11)"/>
  <path d="m.05 0h99.48" transform="translate(8.536 14.11)"/>
 </g>
</svg>

**Comment by RazrFalcon** [comment]
Technically, I should skip such files completely, because `currentColor` is UA-defined and can be anything.

Will think about what can be done here.
