### ISSUE TITLE
fill="#0"

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#123]
Processing [File:Dojikko2.3.svg](https://commons.wikimedia.org/wiki/File:Dojikko2.3.svg) with
> svgcleaner.exe [Dojikko2.3.svg](https://upload.wikimedia.org/wikipedia/commons/3/36/Dojikko2.3.svg) output.svg

lead to an error: `Error: invalid color at 25591:16.`
Here is a minimal working example:
[min.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1594011/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 430 208" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <text x="3" y="80" fill="#0" font-size="36">text</text>
</svg>

```

according to https://validator.w3.org/#validate_by_input my minimal working example is valid

**Comment by RazrFalcon** [comment]
This validator is broken. Forget about it.

This color is invalid. That's it. Viewer will skip it and replace by default. It's a UA-specific behavior, so this can't be done in the svgcleaner.
