### ISSUE TITLE
--paths-to-relative mistake

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#124]
Processing [File:Dojikko2.3.svg](https://commons.wikimedia.org/wiki/File:Dojikko2.3.svg) with
> svgcleaner.exe [Dojikko2.3.svg](https://upload.wikimedia.org/wikipedia/commons/3/36/Dojikko2.3.svg) output.svg  --paths-to-relative yes

lead to an mistake (display it in Chrome/Inkscape):
Here is a minimal working example:
[min.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1594745/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg enable-background="new" viewBox="0 0 2700 1800" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <path d="m1903 1426 8.281 16.88 17.78-6.062-26.06-10.81zl-26.16 10.81 17.91 6.062 8.25-16.88zm-26.16 10.81-10.81 25.69 17-8.125-6.188-17.56zm-10.81 25.69 10.81 25.84 6.188-17.69-17-8.156zm10.81 25.84 26.16 10.66-8.25-16.75-17.91 6.094zm26.16 10.66 26.06-10.66-17.78-6.094-8.281 16.75zm26.06-10.66 10.91-25.84-17.09 8.156 6.188 17.69zm10.91-25.84-10.91-25.69-6.188 17.56 17.09 8.125z" stroke="#000" fill="#999"/>
</svg>

```

**Comment by Perhelion** [comment]
I get no fault.

**Comment by JoKalliauer** [comment]
@Perhelion  If you don't see the Problem of the original file please try the minimal working example, than you see a difference.
the Output is:
```svg
<svg enable-background="new" viewBox="0 0 2700 1800" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <filter id="a">
  <feBlend in2="BackgroundImage"/>
 </filter>
 <g filter="url(#a)">
  <path d="m1903 1426 8.281 16.88 17.78-6.062-26.06-10.81zm-1903-1426 1876.84 1436.81 17.91 6.062 8.25-16.88zm1876.84 1436.81-10.81 25.69 17-8.125-6.188-17.56zm-10.81 25.69 10.81 25.84 6.188-17.69-17-8.156zm10.81 25.84 26.16 10.66-8.25-16.75-17.91 6.094zm26.16 10.66 26.06-10.66-17.78-6.094-8.281 16.75zm26.06-10.66 10.91-25.84-17.09 8.156 6.188 17.69zm10.91-25.84-10.91-25.69-6.188 17.56 17.09 8.125z"/>
 </g>
</svg>

```

If you don't see anything at all (f.e. in Firefox) please try open the files Chrome or Inkscape.

**Comment by Perhelion** [comment]
The original (your code!?) and the compressed file, which gets only **`lineto`** statements (which seems not needed anyway) are nearly the same. So I got  absolutely no difference (in all viewer/editor I have).
<?xml version="1.0"?>
<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
<path d="m40 3.25l8.281 16.88 17.78-6.062-26.06-10.81zl-26.16 10.81 17.91 6.062 8.25-16.88zm-26.16 10.81l-10.81 25.69 17-8.125-6.188-17.56zm-10.81 25.69l10.81 25.84 6.188-17.69-17-8.156zm10.81 25.84l26.16 10.66-8.25-16.75-17.91 6.094zm26.16 10.66l26.06-10.66-17.78-6.094-8.281 16.75zm26.06-10.66l10.91-25.84-17.09 8.156 6.188 17.69zm10.91-25.84l-10.91-25.69-6.188 17.56 17.09 8.125z" fill="#999" stroke="#f0f"/>
</svg>

**Comment by Perhelion** [comment]
@JoKalliauer Oh I see now, I used version 0.91 where this bug is not.

**Comment by JoKalliauer** [comment]
Let's take your code, it is a bit simpler:
Input.svg
```svg
<?xml version="1.0"?>
<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg">
<path d="m40 3.25l8.281 16.88 17.78-6.062-26.06-10.81zl-26.16 10.81 17.91 6.062 8.25-16.88zm-26.16 10.81l-10.81 25.69 17-8.125-6.188-17.56zm-10.81 25.69l10.81 25.84 6.188-17.69-17-8.156zm10.81 25.84l26.16 10.66-8.25-16.75-17.91 6.094zm26.16 10.66l26.06-10.66-17.78-6.094-8.281 16.75zm26.06-10.66l10.91-25.84-17.09 8.156 6.188 17.69zm10.91-25.84l-10.91-25.69-6.188 17.56 17.09 8.125z" fill="#999" stroke="#f0f"/>
</svg>

```
![input](https://user-images.githubusercontent.com/15687581/34467181-1957faae-eeea-11e7-9ff1-e27fde69b62f.png)



Then use the code
> svgcleaner Input.svg output.svg --apply-transform-to-gradients yes --apply-transform-to-shapes yes --convert-shapes yes --group-by-style yes --indent 1 --join-arcto-flags no --join-style-attributes no --merge-gradients yes --regroup-gradient-stops yes --remove-comments yes --remove-declarations no --remove-default-attributes yes --remove-desc yes --remove-dupl-cmd-in-paths yes --remove-dupl-fegaussianblur yes --remove-dupl-lineargradient yes --remove-dupl-radialgradient yes --remove-gradient-attributes yes --remove-invalid-stops yes --remove-invisible-elements yes --remove-metadata yes --remove-needless-attributes yes --remove-nonsvg-attributes yes --remove-nonsvg-elements no --remove-text-attributes yes --remove-title yes --remove-unreferenced-ids yes --remove-unresolved-classes yes --remove-unused-coordinates yes --remove-unused-defs yes --remove-version yes --remove-xmlns-xlink-attribute yes --resolve-use yes --simplify-transforms yes --trim-colors yes --trim-ids yes --trim-paths yes --ungroup-defs yes --ungroup-groups yes --use-implicit-cmds yes --allow-bigger-file --list-separator comma

output.svg:
```svg
<?xml version="1.0"?>
<svg viewBox="0,0,80,80" xmlns="http://www.w3.org/2000/svg">
 <path d="m40 3.25 8.281 16.88 17.78-6.062-26.06-10.81zm-40-3.25 13.84 14.06 17.91 6.062 8.25-16.88zm13.84 14.06-10.81 25.69 17-8.125-6.188-17.56zm-10.81 25.69 10.81 25.84 6.188-17.69-17-8.156zm10.81 25.84 26.16 10.66-8.25-16.75-17.91 6.094zm26.16 10.66 26.06-10.66-17.78-6.094-8.281 16.75zm26.06-10.66 10.91-25.84-17.09 8.156 6.188 17.69zm10.91-25.84-10.91-25.69-6.188 17.56 17.09 8.125z" fill="#999" stroke="#f0f"/>
</svg>

```
![output](https://user-images.githubusercontent.com/15687581/34467182-1d373dec-eeea-11e7-9261-ca21f9444e17.png)

I kind of connects one path to the origin. (Pictures created with Inkscape)
