### ISSUE TITLE
MacOS version no longer works?

### ISSUE THREAD

**Issue by sigtm** [RazrFalcon/svgcleaner#128]
Apologies if this is just happening on my end. Trying to clean any file fails, and if I hover my mouse over the red "X" icon in the status column, MacOS logs out.

I am using the version contained here, on High Sierra 10.13.2:
https://github.com/RazrFalcon/svgcleaner-gui/releases/download/v0.9.2/svgcleaner_macos_0.9.2.zip

I also tried v0.9.1, same issue. I updated today, and have also updated MacOS recently – I'm not quite sure which one caused this to start happening, but last week I had no problems.

If it helps, I'm seeing this in my console when I attempt to clean an SVG file:

LSExceptions shared instance invalidated for timeout.

**Comment by sigtm** [comment]
Correction: the above message (LSExceptions) happens 7-10 seconds after I open the app. When I drop an SVG file in the SVG Cleaner window, I get this:

`MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported`

**Comment by RazrFalcon** [comment]
Everything works perfect on 10.10 and I don't have 10.13 to test it.

The errors you provided has nothing to do with svgc. Probably a macOS bug.

**Comment by sigtm** [comment]
Hmm weird. To clarify, the errors mentioned are attributed to the SVG Cleaner process, but I'm not a dev so it's all greek to me. A quick google does seem to suggest that it might be a 10.13 issue.

**Comment by RazrFalcon** [comment]
Yes. They could have been raised because of svgcleaner, but errors itself was produced by the OS, not the app.

**Comment by RazrFalcon** [comment]
Need more info. Closing for now.
