### ISSUE TITLE
Transforms Not Applied to Paths

### ISSUE THREAD

**Issue by mikebronner** [RazrFalcon/SVGCleaner#13]
For some reason Transforms created in Sketch 3 are no longer applied to the paths. I can provide samples if that helps.

**Comment by Vasilich** [comment]
Hi RazrFalcon,
have you had time to implement this feature?

**Comment by RazrFalcon** [comment]
Hello. Still no...

**Comment by ChALkeR** [comment]
Paths with `c` or `q` are also not transformed, correct?

**Comment by RazrFalcon** [comment]
Yeap... https://github.com/RazrFalcon/SVGCleaner/blob/master/src/cli/paths.cpp#L220
This is some crazy math with this paths and don't really understand it.

**Comment by ChALkeR** [comment]
And what's wrong with just applying the transformation matrix to the numbers that define the curve?

**Comment by ChALkeR** [comment]
Afaik, Bézier curves are just defined by a set of (absolute or relative positioned) points. Transforming them shouldn't be harder than transforming `l`/`L`.

**Comment by RazrFalcon** [comment]
It's not that easy, believe me. Even 'c' segment not always transformed correctly. And there is lots of the restrictions for path to be transformed.
By now I don't have enough time to sort it out.

If you think it's easy - I'm waiting for yours pull request.

**Comment by ChALkeR** [comment]
> Even 'c' segment not always transformed correctly.
Do you have an example of such a path?
I want to test a trivial transformation script.
Just no arcs, plase =).

**Comment by RazrFalcon** [comment]
Yeap.
`<path d="m 150,100 0,100 -200,0 0,-100 z" transform="matrix(0 1 -1 0 0 0 )"/>`
Result must be:
`m -100,150 -100,0 0,-200 100,0 z`
It's simple exmaple, but it didn't work.

**Comment by ChALkeR** [comment]
But it works with a simple algorithm that just applies the transform to
every point of the original path.​ That's what I was talking about.
What paths envolve crazy math, except for the arcs?

**Comment by RazrFalcon** [comment]
You right. Bug was in algorithm which converts segments into curves.
I just had no time to find it out.
I think that I fix this issue soon.

**Comment by RazrFalcon** [comment]
Done. But it make files usually bigger than without transform baking. So it's useless. I don't know what else could be done.

**Comment by Vasilich** [comment]
sometimes the reason isn't to get svg file really smaller, but to simplify it. So for those cases removing all kind of transformations is a big help.

**Comment by mikebronner** [comment]
@Vasilich agree there completely! :)

**Comment by Vasilich** [comment]
Hi RazrFalcon, 
is there any chance for this to get implemented?

**Comment by RazrFalcon** [comment]
Hello. It's already implemented, but you need to build it from source.

**Comment by Vasilich** [comment]
any instructions on how to compile it under Windows? i tried to download Qt5, but it seems that SVGCleaner need Qt4, and i don't see it in docs.

**Comment by Vasilich** [comment]
installed Qt 4.8.6 and haven't managed to compile cli project :(

**Comment by RazrFalcon** [comment]
I don't have build environment for SVGCleaner anymore, so I can't recompile it quickly.
Building is simple:
```
qmake
make
```
