### ISSUE TITLE
CurrentColor failed compile

### ISSUE THREAD

**Issue by JmRy** [RazrFalcon/svgcleaner#135]
Hello,

Very good job and very helpful, but could you remove the _[failed to resolved attribute 'fill']_ error that is generated when using currentColor ? 

It seems that there was not this problem in previous versions.

Thank you in advance

**Comment by RazrFalcon** [comment]
If `currentColor` can't be resolved -  it's an error. It can't be fixed because `currentColor` is UA-specific value. `svgcleaner` is designed for self-contained SVG.

**Comment by RazrFalcon** [comment]
This can't be resolved without a context. And preserving of the `currentColor` isn't support at the moment.
