### ISSUE TITLE
 xml:space="preserve" ignored, replaces text with options --remove-text-attributes no --indent 1

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#137]
Processing [File:Barcelona.svg](https://commons.wikimedia.org/wiki/File:Barcelona.svg) with
>svgcleaner [Barcelona.svg](https://upload.wikimedia.org/wikipedia/commons/2/2c/Barcelona.svg) output.svg --remove-text-attributes no --indent 1
replaces the text Barcelona.

Minimal Working example:
[min.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1866701/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 168.79 36.58" xmlns="http://www.w3.org/2000/svg">
 <path d="m.84.84h167.11v34.9h-167.11z" fill="#d3e3e3" stroke="#1b4157" stroke-dashoffset="8" stroke-width="1.68"/>
 <text fill="#1b4157" font-family="'DejaVu Sans Condensed'" font-size="30" font-weight="bold" line-height="100%" stroke="#44718a" transform="matrix(1.0562 0 0 .9468 -334.05 -332.99)" x="318.99" xml:space="preserve" y="379.98"><tspan>Barcelona</tspan></text>
</svg>
```
![min](https://user-images.githubusercontent.com/15687581/38177419-71832786-3601-11e8-977f-5a8e51f7ad75.png)

Output:
[output.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1866702/output.svg.txt)
```svg
<svg viewBox="0 0 168.79 36.58" xmlns="http://www.w3.org/2000/svg">
 <path d="m.84.84h167.11v34.9h-167.11z" fill="#d3e3e3" stroke="#1b4157" stroke-dashoffset="8" stroke-width="1.68"/>
 <text fill="#1b4157" font-family="'DejaVu Sans Condensed'" font-size="30" font-weight="bold" line-height="100%" stroke="#44718a" transform="matrix(1.0562 0 0 .9468 -334.05 -332.99)" x="318.99" xml:space="preserve" y="379.98">
  <tspan>Barcelona</tspan>
 </text>
</svg>
```
![output](https://user-images.githubusercontent.com/15687581/38177422-7861963c-3601-11e8-8082-48229b71bd34.png)

PS: I use `--remove-text-attributes no` as a workaround for https://github.com/scour-project/scour/issues/160

**Comment by RazrFalcon** [comment]
Fixed by https://github.com/RazrFalcon/libsvgdom/commit/f7cc894dea4858acd1bdd829eac55f7ac0d96908
