### ISSUE TITLE
SVG becomes blank after optimization

### ISSUE THREAD

**Issue by kornelski** [RazrFalcon/svgcleaner#139]
Test case:

https://github.com/ImageOptim/ImageOptim/files/1890151/download.svg.zip

Originally reported at:

https://github.com/ImageOptim/ImageOptim/issues/256

**Comment by RazrFalcon** [comment]
I confirm.

**Comment by RazrFalcon** [comment]
Turns out it was already fixed in a master. Will publish a new release soon.
