### ISSUE TITLE
--remove-nonsvg-elements no keeps <sodipodi:namedview/>, but prefix xmlns:sodipodi deleted

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#141]
Prozessing a file in Inkscape and saved as Inkscape-svg (default option in Inkscape) adds a `<sodipodi:namedview`-tag
prozessing such a file with
> svgcleaner Inksape.svg output.svg --remove-nonsvg-elements no

leads to an error.

[Inkscape.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1904230/Inkscape.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg height="321.57" viewBox="0 0 29648.87 32162.91" width="296.49"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd">
<sodipodi:namedview pagecolor="#ffffff" bordercolor="#666666" borderopacity="1" objecttolerance="10" gridtolerance="10" guidetolerance="10" inkscape:pageopacity="0" inkscape:pageshadow="2" inkscape:window-width="640" inkscape:window-height="480" id="namedview139" showgrid="false" inkscape:zoom="0.33380481" inkscape:cx="81.095887" inkscape:cy="86.96167" inkscape:window-x="0" inkscape:window-y="0" inkscape:window-maximized="0" inkscape:current-layer="svg137" />
</svg>
```

[output.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/1904232/output.svg.txt)
```svg
<svg height="321.57" viewBox="0 0 29648.87 32162.91" width="296.49" xmlns="http://www.w3.org/2000/svg">
<sodipodi:namedview/>
</svg>
```

After Inkscape it makes sense too specify this option, because of  #115

**Comment by RazrFalcon** [comment]
Yes. You must specify `--remove-nonsvg-attributes` too.

**Comment by JoKalliauer** [comment]
I think a Warning would be great if someone calls svgcleaner with `--remove-nonsvg-elements no --remove-nonsvg-attributes yes`.
