### ISSUE TITLE
Removing empty rect elements

### ISSUE THREAD

**Issue by brandondurham** [RazrFalcon/svgcleaner#143]
I have `<rect />` elements in all of my SVGs that look something like this:

```
<rect width="2250" height="36" fill="#fff" opacity="0"/>
```

They’re required for legacy reasons in the project I’m working on. When running the SVGs through SVGCleaner performance is improved dramatically, but the layout is broken because of the missing `<rect />` element.

I’ve tried many of the settings but haven’t found anything that’s directly responsible for this. Is there anything I can do to ensure these elements make it through the optimization?

**Comment by RazrFalcon** [comment]
>but the layout is broken because of the missing <rect /> element

Shapes can't impact the layout, afaik. Can you provide a minimal example?

Also, svgcleaner doesn't support removing of the transparent elements yet. So the rect from your example will not be removed.

**Comment by brandondurham** [comment]
Okay, I discovered that it converts it to a path. The `<rect />` above becomes this:

```
<path d="m0 0h2250v36h-2250z" fill="#fff" opacity="0"/>
```

I was specifically targeting a `<rect />` which is why it was breaking.

**Comment by RazrFalcon** [comment]
Then you should disable [Convert basic shapes into paths](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc#convert-basic-shapes-into-paths).

**Comment by brandondurham** [comment]
Fantastic. Thank you so much!
