### ISSUE TITLE
Invalid color "transparent"

### ISSUE THREAD

**Issue by pickfire** [RazrFalcon/svgcleaner#147]
Generated from `dot` (graphviz).

```svg
...
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-633 1150,-633 1150,4 -4,4"/>
...
```

**Comment by RazrFalcon** [comment]
Yes. It's a known `graphviz` bug. There are no `transparent` color in SVG. So your SVG file is invalid.

**Comment by pickfire** [comment]
Oh, so it's a bug in SVG but not `svgcleaner`. Closing this issue.
