### ISSUE TITLE
Preserve CSS before removing or converting to attributes.

### ISSUE THREAD

**Issue by extended83** [RazrFalcon/svgcleaner#164]
I think it's very nice and configurable tool, but it looks like there's no option to preserve inline css before removing or converting to attributes. I need to optimize files but keep CSS because I can simply reference to this and for example change color of some elements on hover or on some actions in website.

**Comment by RazrFalcon** [comment]
It's not possible and not planned. I must resolve CSS before processing. It can't be optional.
