### ISSUE TITLE
Error: the attribute 'offset' is missing in the 'stop' element. (Referencing LineNr)

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#166]
Prozessing the invalid file [File:Oxygen480-mimetypes-hidef-application-x-gzpostscript.svg](https://commons.wikimedia.org/wiki/File:Oxygen480-mimetypes-hidef-application-x-gzpostscript.svg) leads to this error: `Error: the attribute 'offset' is missing in the 'stop' element.`

I would like know the line of this issue, maybe you could add this in the error-message.

**Comment by RazrFalcon** [comment]
It's not possible at this stage.
