### ISSUE TITLE
Target a folder instead of a file

### ISSUE THREAD

**Issue by brandondurham** [RazrFalcon/svgcleaner#171]
I’m looking to process a folder with hundreds of SVGs. I know this is possible [using other methods](https://gist.github.com/j3j5/549d1f871dbcae6deab767bfc1464fa0), but I’m wondering if there are any native methods.

**Comment by RazrFalcon** [comment]
Using [GUI](https://github.com/RazrFalcon/svgcleaner-gui)?

**Comment by brandondurham** [comment]
Using the CLI currently.

**Comment by RazrFalcon** [comment]
Using Bash, Python or anything else. There are too many ways to do this. I don't plan to implement this in CLI.
