### ISSUE TITLE
Improvement: --resolve-use does not resolve use

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#173]
Prozessing https://commons.wikimedia.org/wiki/File:Na%2BH2O.svg with

svgcleaner [InOut.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/2435513/InOut.svg.txt) [InOut.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/2435513/InOut.svg.txt) --allow-bigger-file --indent 1 --resolve-use yes

# Input/Output
[InOut.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/2435513/InOut.svg.txt)
```svg
<svg viewBox="0 0 2700 2700" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <defs>
  <circle id="c" fill="#bfbfbf" r="125" stroke="#9a9a9a" stroke-width="2"/>
  <g id="d">
   <use x="160" xlink:href="#c" y="190"/>
   <circle fill="#ca0202" r="225"/>
   <use x="-160" xlink:href="#c" y="190"/>
  </g>
 </defs>
 <use height="100%" transform="translate(1350 1350)" width="100%" xlink:href="#d" y="800"/>
 <use height="100%" transform="matrix(-1 0 0 -1 1350 1350)" width="100%" xlink:href="#d" y="800"/>
 <use height="100%" transform="matrix(.5 -.8 .8 .5 1350 1350)" width="100%" xlink:href="#d" y="800"/>
 <use height="100%" transform="matrix(-.6 -.8 .8 -.6 1350 1350)" width="100%" xlink:href="#d" y="800"/>
 <use height="100%" transform="matrix(.5 .9 -.9 .5 1350 1350)" width="100%" xlink:href="#d" y="800"/>
 <use height="100%" transform="matrix(-.5 .9 -.9 -.5 1350 1350)" width="100%" xlink:href="#d" y="800"/>
</svg>
```

![inout](https://user-images.githubusercontent.com/15687581/46314218-3ea70900-c5ca-11e8-9add-d96c890b70ef.png)

----

It would be nice if the use can be resolved.

----

<details>

<summary> Copyright </summary> 

License: Public Domain

Author: https://de.wikipedia.org/wiki/Benutzer:Taxman

Source: https://commons.wikimedia.org/wiki/File:Na%2BH2O.svg

</details>

**Comment by RazrFalcon** [comment]
What result do you expect?

**Comment by RazrFalcon** [comment]
But it makes the file bigger. And `--resolve-use` works in a different way. So it's out of scope.

**Comment by JoKalliauer** [comment]
This is answered in https://github.com/RazrFalcon/svgcleaner/issues/174#issuecomment-427636939 :
> 
> 
> Maybe you will be interested in [usvg](https://github.com/RazrFalcon/usvg). It's still a beta, but it's what you want.
> 
> And simplification is out of scope for _svgcleaner_.
