### ISSUE TITLE
[Feature] Ungroup and apply transforms to paths/shapes... even if the file grows

### ISSUE THREAD

**Issue by mantielero** [RazrFalcon/svgcleaner#174]
Sometimes I am looking not for a smaller file, but for a simpler one even if it is much bigger. This way I can process it with python.
I'd love to see a "--simple" flag that flattens the files so I can process them easily with python, xmlstarlet, ... 

PS: Congratulations for such an amazing tool. This is the first useful rust tool I have ever used.

**Comment by RazrFalcon** [comment]
Maybe you will be interested in [usvg](https://github.com/RazrFalcon/usvg). It's still a beta, but it's what you want.

And simplification is out of scope for *svgcleaner*.

**Comment by mantielero** [comment]
That's exactly what I am looking for. I will give it a try.

**Comment by RazrFalcon** [comment]
Feel free to write any requests.
