### ISSUE TITLE
Segmentation fault (core dumped) on Ubuntu 18.04

### ISSUE THREAD

**Issue by wilburt** [RazrFalcon/svgcleaner#177]
While I was using Ubuntu 17.10, the GUI app was working quite alright but on Ubuntu 18.04, it first complained of:

> error while loading shared libraries: libQt5Concurrent.so.5: cannot open shared object file: No such file or directory

Then I executed the following: 
```
sudo apt install build-essential
sudo apt install qtcreator
sudo apt install qt5-default
```

But this didn't make it work either as I began to get 

> Segmentation fault (core dumped).

By the way, the command line executable is working quite alright.

Please, is there any way aroundd this error?

**Comment by RazrFalcon** [comment]
Did you get svgcleaner from [here](https://github.com/RazrFalcon/svgcleaner-gui/releases)?

If so, can you run from the terminal. Like `./svgcleaner-gui` and post the output here.

>Then I executed the following

Its not required. It doesn't use system Qt libs anyway.

**Comment by wilburt** [comment]
It simply displayed a dialog that says.

> The 7za executable not found.
> It should be in the application folder.

By the way, the 7za file is in the same folder as svgcleaner-gui executable.

**Comment by RazrFalcon** [comment]
`./7za --help`?

**Comment by wilburt** [comment]
```
7za: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
```

**Comment by RazrFalcon** [comment]
Looks like something wrong with the provided 7z.

You can remove it and link the system one. Something like `rm ./7za; ln -s /usr/bin/7za .`

**Comment by wilburt** [comment]
Thanks this fixed it.

**Comment by btd1337** [comment]
Installing `p7zip` worked for me.

OS: Arch Linux
