### ISSUE TITLE
"The '7za' executable is not found. It should be in the application folder"

### ISSUE THREAD

**Issue by neoh-zz** [RazrFalcon/svgcleaner#178]
After downloading and decompressing the prebuilt x86_64 0.9.5 linux version, running the executable svgcleaner-gui from the folder fails with message: "The '7za' executable is not found. It should be in the application folder", even though the executable 7za clearly exists in the same folder. Changing permission of the executable 7za doesn't help.

Tested in Arch Linux and Fedora 28.

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/svgcleaner/issues/177
