### ISSUE TITLE
page border and shadow enabled after using SVGCleaner

### ISSUE THREAD

**Issue by JanGruuthuse** [RazrFalcon/SVGCleaner#18]
When applying SVGCleaner it enables page border and shadow.
Sample svg without page border and shadow:
https://www.dropbox.com/s/mma67f0g239korg/WithoutPageBorder%26Shadow.svg?dl=0
Sample svg with page border and shadow after apllying SVGCleaner:
https://www.dropbox.com/s/llwovgp7u3j7vfm/WithPageBorder%26Shadow.svg?dl=0

**Comment by RazrFalcon** [comment]
I do not see any border or shadow. What kind of editor/viewer you using?

**Comment by JanGruuthuse** [comment]
Inkscape 0.48.4 r9939 (ubuntu 14.04 lts amd64)

**Comment by JanGruuthuse** [comment]
Inkscape 0.48.4 r9939 (ubuntu 14.04 lts amd64)

**Comment by RazrFalcon** [comment]
SVG Cleaner removes Inkscape specific attributes. Which in not included in SVG standard, so it's technically do not change svg in general.
Still you can disable it by unchecking Inkscape and Sodipodi options.

**Comment by JanGruuthuse** [comment]
OK, my miss understanding of how the endresult looks. Thanks for explaining
