### ISSUE TITLE
removes attributes of svg2.0-Elements (meshgradient)

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/svgcleaner#180]
Prozessing [File:Radar_Mac.svg](https://commons.wikimedia.org/wiki/File:Radar_Mac.svg) with svgcleaner leads to a removement of the [SVG 2.0-Element meshgradient](https://www.w3.org/TR/2013/WD-SVG2-20130409/pservers.html).

>$ svgcleaner input.svg.txt output.svg.txt --allow-bigger-file --indent 1 --remove-nonsvg-attributes no --remove-nonsvg-elements no --remove-unused-defs no --remove-declarations no  --remove-unreferenced-ids no

Warning: Could not resolve the 'fill' IRI reference: a. Fallback to 'none'.

This seems to be related to #126 .

# Input
[Input.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/2538169/Input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg height="80" viewBox="0 0 21.167 21.167" width="80" xmlns="http://www.w3.org/2000/svg">
 <defs>
  <meshgradient id="a" x="61.856" y="379.399" gradientTransform="rotate(-45 -414.2 244.26)" gradientUnits="userSpaceOnUse">
   <meshrow>
    <meshpatch>
     <stop path="c 0,5.77195 -4.67909,10.451 -10.451,10.451" stop-color="#1c0000"/>
     <stop path="l 0,-10.451"/>
     <stop path="l 0,0"/>
     <stop path="l 10.451,0"/>
    </meshpatch>
    <meshpatch>
     <stop path="c -5.77195,0 -10.451,-4.67909 -10.451,-10.451"/>
     <stop path="l 10.451,0"/>
     <stop path="l 0,0"/>
    </meshpatch>
    <meshpatch>
     <stop path="c 0,-5.77195 4.67909,-10.451 10.451,-10.451"/>
     <stop path="l -4.21753e-005,10.451" stop-color="#3e6915"/>
     <stop path="l 4.21753e-005,0" stop-color="#3e6915"/>
    </meshpatch>
    <meshpatch>
     <stop path="c 5.77195,0 10.4511,4.67916 10.451,10.451"/>
     <stop path="l -10.451,-7.35946e-006" stop-color="#7dd32a"/>
     <stop path="l -1.29023e-005,3.08016e-006" stop-color="#7dd32a"/>
    </meshpatch>
   </meshrow>
  </meshgradient>
 </defs>
 <path d="m10.736.133a10.451 10.451 0 0 0 -7.543 3.06 10.451 10.451 0 0 0 0 14.78 10.451 10.451 0 0 0 14.78 0 10.451 10.451 0 0 0 0-14.78 10.451 10.451 0 0 0 -7.237-3.06z" fill="url(#a)" stroke="#7dd32a" stroke-linecap="round" stroke-linejoin="round" stroke-width=".265" paint-order="normal"/>
</svg>

```

# Output
[Output.svg.txt](https://github.com/RazrFalcon/svgcleaner/files/2538172/Output.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg height="80" viewBox="0 0 21.167 21.167" width="80" xmlns="http://www.w3.org/2000/svg">
 <defs>
  <meshgradient>
   <meshrow>
    <meshpatch>
     <stop path="c 0,5.77195 -4.67909,10.451 -10.451,10.451" stop-color="#1c0000"/>
     <stop path="l 0,-10.451"/>
     <stop path="l 0,0"/>
     <stop path="l 10.451,0"/>
    </meshpatch>
    <meshpatch>
     <stop path="c -5.77195,0 -10.451,-4.67909 -10.451,-10.451"/>
     <stop path="l 10.451,0"/>
     <stop path="l 0,0"/>
    </meshpatch>
    <meshpatch>
     <stop path="c 0,-5.77195 4.67909,-10.451 10.451,-10.451"/>
     <stop path="l -4.21753e-005,10.451" stop-color="#3e6915"/>
     <stop path="l 4.21753e-005,0" stop-color="#3e6915"/>
    </meshpatch>
    <meshpatch>
     <stop path="c 5.77195,0 10.4511,4.67916 10.451,10.451"/>
     <stop path="l -10.451,-7.35946e-006" stop-color="#7dd32a"/>
     <stop path="l -1.29023e-005,3.08016e-006" stop-color="#7dd32a"/>
    </meshpatch>
   </meshrow>
  </meshgradient>
 </defs>
 <path d="m10.736.133a10.451 10.451 0 0 0 -7.543 3.06 10.451 10.451 0 0 0 0 14.78 10.451 10.451 0 0 0 14.78 0 10.451 10.451 0 0 0 0-14.78 10.451 10.451 0 0 0 -7.237-3.06z" fill="none" stroke="#7dd32a" stroke-linecap="round" stroke-linejoin="round" stroke-width=".265" paint-order="normal"/>
</svg>
``` 

<details>

<summary>Copyright</summary>

Iicense: LGPL

Author: Habitator terrae

source: https://commons.wikimedia.org/wiki/File:Radar_Mac.svg

</details>

**Comment by RazrFalcon** [comment]
As well as SVG Tiny 1.2. This is strictly SVG 1.1 Full cleaner. I should mention it somewhere.

**Comment by JoKalliauer** [comment]
> 
> 
> As well as SVG Tiny 1.2. This is strictly an SVG 1.1 Full cleaner. I should mention it somewhere.

does it mean `--remove-nonsvg-attributes no` is a feature that won't get developed any more?

**Comment by RazrFalcon** [comment]
You can't fix it with flags. It's just not supported. Mostly because 99.9% of SVG images are SVG 1.1 Full complain. So I didn't bother.

**Comment by JoKalliauer** [comment]
> 
> 
> moreover, looking at the source @JoKalliauer posted, the Wikimedia shows 2 errors
> https://validator.w3.org/check?uri=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilepath%2FRadar_Mac.svg&doctype=Inline&ss=1
> So I am not sure whether it was a good idea to use latest SVG definitions on Wiki, that has issues with W3C validator.

**latest SVG definitions**
In Wikipedia everyone can upload any Text-file as *.svg. (Only a few keywords like "xlink:href" are blocked for security-reasons.) Therfore everyone can upload SVG 1.2 ([Working Draft 2005](https://www.w3.org/TR/SVG12/)) and SVG 2.0 ([Working Draft 2018](https://www.w3.org/TR/SVG2/), even they are not published till now. meshgradient was published in [2003](https://www.w3.org/TR/2013/WD-SVG2-20130409/pservers.html).

**issues with W3C validator**
W3C can only check against SVG 1.0-DTD or SVG 1.1-DTD
But your link is the nu-validator (without DTD):
https://validator.nu/?doc=https://upload.wikimedia.org/wikipedia/commons/2/21/Radar_Mac.svg&group=1&schema=http%3A%2F%2Fs.validator.nu%2Fsvg-xhtml5-rdf-mathml.rnc+http%3A%2F%2Fs.validator.nu%2Fhtml5%2Fassertions.sch+http%3A%2F%2Fc.validator.nu%2Fall%2F&parser=xml
W3C just claims it to be its own result
And nu-validator checks against "SVG 1.1 + HTML + MathML 3.0"
So it is a valid SVG2.0-file, but there is no validator for SVG 2.0

**Comment by RazrFalcon** [comment]
@JoKalliauer but wiki uses librsvg, which doesn't support SVG 2 at all. And so as most of the browsers. SVG 2 is still a draft. No one should support it yet.

**Comment by JoKalliauer** [comment]
> 
> 
> @JoKalliauer but wiki uses librsvg, which doesn't support SVG 2 at all. And so as most of the browsers. SVG 2 is still a draft. No one should use it yet.

I know but [Habitator terrae](https://commons.wikimedia.org/w/index.php?title=Special:ListFiles&offset=2018102718&user=Habitator+terrae&ilshowall=1) uploaded the SVG2.0-file, I just cleaned it up because of another librsvg-SVG1.1-bug.

I would like to remove the SVG 2.0-feature, but I don't know if it is possible to create the following with SVG 1.1:
![input](https://user-images.githubusercontent.com/15687581/47870642-54e2f780-de0a-11e8-9fe6-3ce9a9f2647c.png)

As long as you just use Inkscape it might be fine, but only pngs/PDF should be used to render such files.

**Comment by RazrFalcon** [comment]
The problem is that is should look correctly on wiki, but it's not. So it's already broken.

Anyway, it will not be supported until SVG 2 became a new standard.

**Comment by JoKalliauer** [comment]
> @JoKalliauer but wiki uses librsvg, which doesn't support SVG 2 at all. And so as most of the browsers. 
most browsers support:
- [phab:T43426](https://phabricator.wikimedia.org/T43426) hsl colors f.e. [Xclamation_blue_1.svg](https://upload.wikimedia.org/wikipedia/commons/archive/2/2b/20180829084333%21Xclamation_blue_1.svg)
- `style="`[`paint-order`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order)`:stroke fill markers;"` f.e. [Horseshoe_schema_Uwe_Backes.svg](https://upload.wikimedia.org/wikipedia/commons/archive/7/72/20181105031743%21Horseshoe_schema_Uwe_Backes.svg)

I agree on that if a svg-file is shared with another person SVG 1.1 should be used, thats the reason, why I closed this bug.

>  Mostly because 99.9% of SVG images are SVG 1.1 Full complain.

I would say 60% of SVG-files are W3C-SVG1.1-DTD-invalid (spaces in id-names, editor-data, grids, guidlines,rdf-metadata, ...)
I see SVG1.2 and SVG 2.0 as a sub-group of invalid SVG 1.1-files.
I know most invalid SVG1.1-files are rendered correctly, because the invalid Elements/Attributes are not rendered.

I agree on that it does not make sence to optimize invalid SVG1.1-Elements/Attributes, but in my opinion it does make sense to optimize invalid SVG1.1-files, since they are very common.
In my opinion it is necessary to keep non-svg-elements such as metadata (f.e.:Author) or editor-data (f.e grid). I guess svgcleaner treats SVG1.2 and SVG2.0 elements as non-svg-elements, but removes valid svg-elements, since they non-svg should not be rendered?

But some invalid Files, such as [File:Działanie dławika przeciwzwarciowego 1.svg](https://commons.wikimedia.org/wiki/File:Dzia%C5%82anie_d%C5%82awika_przeciwzwarciowego_1.svg) get broken with ` --no-defaults`
>svgcleaner [Działanie_dławika_przeciwzwarciowego_1.svg](https://upload.wikimedia.org/wikipedia/commons/2/29/Dzia%C5%82anie_d%C5%82awika_przeciwzwarciowego_1.svg) Output.svg --no-defaults

![dzialanie_dlawika_przeciwzwarciowego_1](https://user-images.githubusercontent.com/15687581/48023333-c63de580-e13d-11e8-97d8-ea80635ece69.png) |<-before and after->|![output](https://user-images.githubusercontent.com/15687581/48023335-c76f1280-e13d-11e8-9aac-71ef0fc636f1.png)

> This is strictly an SVG 1.1 Full cleaner.

With SVG 1.1 you mean valid SVG 1.1, or also invalid SVGs? (and what kind of invalidity?)
