### ISSUE TITLE
Option to force all shapes to paths?

### ISSUE THREAD

**Issue by mrbluecoat** [RazrFalcon/svgcleaner#183]
Regarding [convert-shapes](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc#convert-basic-shapes-into-paths), I understand the logic behind ignoring `circle`, `ellipse`, and rounded `rect` to optimize filesize but can you add an option to force convert those anyways?  [Maker.js](https://maker.js.org/) only supports [path importing](https://maker.js.org/docs/importing/#SVG%20path%20data).

**Comment by RazrFalcon** [comment]
You can try https://github.com/RazrFalcon/usvg, but it's still a *beta*.

**Comment by mrbluecoat** [comment]
Cool, between that and svgo as a fallback I should be good to go.  Thanks.
