### ISSUE TITLE
File extension doesn't dictate file contents

### ISSUE THREAD

**Issue by DaveJarvis** [RazrFalcon/svgcleaner#195]
```
$ svgcleaner x.svg.txt x-out.svg
Error: Invalid value for '<in-file>': The file format must be SVG.
```

This error is technically incorrect. The file format _is_ SVG, but the extension is `.svg.txt`.

Try to confirm whether the file is SVG by detecting an `<svg` XML element within an XML file, rather than using the filename extension.

**Comment by RazrFalcon** [comment]
The extension must be `svg`.

**Comment by JoKalliauer** [comment]
allowing *.svg *.xml and *.txt would be great (txt because of github)
