### ISSUE TITLE
svgcleaner -cli terminates in "unusual way"

### ISSUE THREAD

**Issue by durehed** [RazrFalcon/SVGCleaner#20]
Hi!

Running svg cleaner in cli through ANT build and when sag cleaner runs into problems it terminates in "an unusual way" according to ANT.

The problem is that SVG Cleaner gets into trouble converting height to px. I'm working around this issue since the problematic value of height is due to a failure in a previous transformation of the svg. 

This is just to inform about that this issue might arise when there is an error in converting with svg cleaner as cli.

```
[echo] Clean pixelized/101757.svg
[exec] The initial file size is: 1308308
[exec] The initial number of elements is: 2779
[exec] The initial number of attributes is: 9630
[exec] Error: could not convert height to px
[exec]
[exec] This application has requested the Runtime to terminate it in an unusual way.
[exec] Please contact the application's support team for more information.
[exec] Result: 3
´´´

**Comment by RazrFalcon** [comment]
Nope. You a bit wrong. It's not a random error. It's intentional stopping of cleaning.
There are plenty of such errors, because some thing svgcleaner just cannot understand or process - so it simply shutdowns to prevent creating broken file.
So your example is pretty usual. And, also, can be recreated in GUI.

**Comment by durehed** [comment]
Yes, I'm not saying giving an error is wrong or random I'm saying that ANTS exec task is saying "unusual".

This error showed up because I had provided an SVG with bad height and width values, as I said. So I'm not surprised or questioning that there was an error. I'm just informing that this was considered requesting the runtime "to terminate in an unusual way" according to ANT.

Also the real problem I think is that a user should not be presented with information that "svgcleaner-cli-exe has stopped working" when in fact it's a conversion that has stopped. Its not good UI design and I guess the ANT exec task is hinting that too.

![error_svgcleaner_png](https://cloud.githubusercontent.com/assets/1753054/6056849/024c869e-ad17-11e4-9361-1ec2515da595.png)

**Comment by RazrFalcon** [comment]
I see. Maybe Qt macros qFatal(), which I used, cause this problem. I'll look into it.

**Comment by RazrFalcon** [comment]
Fixed.
