### ISSUE TITLE
Svg is changed after minimization

### ISSUE THREAD

**Issue by matklad** [RazrFalcon/svgcleaner#208]
I've tried `svgcleaner` on my file, it worked without any errors, but the result rendered differently:

https://gist.github.com/matklad/0eea6313763d37eaf580cd424261a662

![image](https://user-images.githubusercontent.com/1711539/72441859-b000d000-37ab-11ea-8f5e-ff88ba03c5b3.png)

![image](https://user-images.githubusercontent.com/1711539/72441887-b98a3800-37ab-11ea-97fa-f8bc247b9712.png)

I don't know anything about svg, so it's maybe somehting wrong on my side?

**Comment by matklad** [comment]
Huh, just checked, and maybe it's the Firefox who renders it wrong? Both versions look the same in chrome: 
![Uploading image.png…]()

**Comment by RazrFalcon** [comment]
Yes, looks like a Firefox bug:

![logo min](https://user-images.githubusercontent.com/725494/72442698-aa0fec80-37b5-11ea-8e13-0319e43f1e44.png)

Look like it ignores `font-size` on `tspan`. Firefox has a pretty bad SVG Text support in general.

Here is a fixed version:

```xml
<svg height="24.747536mm" viewBox="0 0 85.797134 24.747536" width="85.797134mm" xmlns="http://www.w3.org/2000/svg">
    <g transform="translate(-29.534624 -59.398722)" font-family="Fira Code" font-size="10.6" font-weight="bold">
        <text stroke-width=".264583" x="30.918449" y="68.702377">rust.</text>
        <path d="m60.730652 71.342285 h 54.407944 v 12.607942 h -54.407944 z" fill="#30363b" stroke="#20262b" stroke-width=".392058"/>
        <text fill="#fff" stroke-width=".264583" x="62.535698" y="80.762833">analyzer</text>
    </g>
</svg>
```

**Comment by matklad** [comment]
Yeah, I guess this can be closed than!
