### ISSUE TITLE
]> being converted to ]&gt;

### ISSUE THREAD

**Issue by llandrew** [RazrFalcon/SVGCleaner#21]
So when running an SVG file through the cleaner, it always breaks the file by replacing the trailing '>' with '&gt;'. I've tried unchecking every option and it still occurs. This is the bit of code at the top of the file it's affecting.

I don't know if this is a bug or I'm missing something I can do to keep it from replacing that. Any help would be appreciated. Thanks

```
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [
    <!ENTITY ns_extend "http://ns.adobe.com/Extensibility/1.0/">
    <!ENTITY ns_ai "http://ns.adobe.com/AdobeIllustrator/10.0/">
    <!ENTITY ns_graphs "http://ns.adobe.com/Graphs/1.0/">
    <!ENTITY ns_vars "http://ns.adobe.com/Variables/1.0/">
    <!ENTITY ns_imrep "http://ns.adobe.com/ImageReplacement/1.0/">
    <!ENTITY ns_sfw "http://ns.adobe.com/SaveForWeb/1.0/">
    <!ENTITY ns_custom "http://ns.adobe.com/GenericCustomNamespace/1.0/">
    <!ENTITY ns_adobe_xpath "http://ns.adobe.com/XPath/1.0/">
]>
```

**Comment by RazrFalcon** [comment]
Hello. It's bug of XML parser. You can check "Remove XML prolog" to fix your problem.
Or you can build SVGCleaner from git, where it's alredy fixed by moving to another XML parser. But it's  unstable. So you can wait for next release.
