### ISSUE TITLE
Do a 1.0.0 release of svgcleaner

### ISSUE THREAD

**Issue by aaronfranke** [RazrFalcon/svgcleaner#219]
`svgcleaner`'s last release was over 2 years ago. After that point, there has been very little development, but there still has been some, so it would make sense to do a release at some point.

Since `svgcleaner` is very stable by now and [kinda abandoned](https://github.com/RazrFalcon/svgcleaner/pull/210#issuecomment-581083397), I suggest that this new version be called 1.0.0 instead of 0.9.6 or similar. This can potentially be the last release unless @RazrFalcon wants to pick it up again.

Thanks in advance, I would very much appreciate having `--append-newline` available when using `cargo install svgcleaner`.

**Comment by RazrFalcon** [comment]
Because of the nature of `svgcleaner`, there will be no 1.0/stable release.

>is very stable

It's very broken. That's why it's abandoned.

**Comment by JoKalliauer** [comment]
> It's very broken. That's why it's abandoned.
Compared to svgo svgcleaner is very stable.

Svgcleaner and scour are roughly similar stable (per file), but svgcleaner has more features, so the stability of svgcleaner per feature/file-reduction seems to be the highest comparet to the other two big players.

However imho the only downside of svgcleaner (regarding stability), you cannot dissable some features. (I know dissableing would lead to further bugs, but I sometimes like to run a specific function, without chaning the rest of the file, but dissabling-preprocessing-features could be only changed while adding --allow-alpha-features .)

**Comment by RazrFalcon** [comment]
>I sometimes like to run a specific function, without chaning the rest of the file

This is literal impossible to implement.
