### ISSUE TITLE
Font size problem

### ISSUE THREAD

**Issue by mireiner** [RazrFalcon/svgcleaner#220]
Hi,

I got SVG image files created using Qt SVG. The orginal SVG files are rendered fine in Firefox, Chromium and new Microsoft Edge browsers. But the cleaned files are rendered only fine in Chromium 86.x browser. But in Firefox 81.x and Microsoft Edge browser the font size doesn't match the original SVG file. Tested on Windows 10 64bit latest version.

Test case files:
https://www.dropbox.com/s/kjfcoudo2nzd0qn/SVG%20Cleaner%20Test%20Files.zip?dl=0

**Comment by RazrFalcon** [comment]
Looks like a Firefox bug to me. All other applications are fine.

You can set *Join presentational attributes* to *None* as a work around. But this is not a svgcleaner bug.
