### ISSUE TITLE
Option to preserve some newlines & tabs

### ISSUE THREAD

**Issue by TPS** [RazrFalcon/svgcleaner#222]
@RazrFalcon It'd be great to have an option to convert _required_ (non-eliminable) whitespace sequences made solely of
1. (`CR LF` [other whitespace]) to just `LF`
2. (`Tab` [non-{`CR`,`LF`} whitespace]) to just `Tab`
3. (non-[`CR`,`LF`,`Tab`] whitespace) to `Space` _(similar to current)_
4. _Further option:_ Convert some remaining `space`s to `LF` to break up over-long _(configurable)_ 1-liners efficiently

This will keep filesize minimal, while allowing to more easily compare by eye (or GitHub Δ comparison 😉) or edited by hand via any modern (i.e., basically anything newer than Windows Notepad 🙄) text editor.  The sole downside I can think of that it _might_ worsen SVG***Z*** sizes for those who use that, but maybe another further option to retain the current behavior would solve that.

_N.B.:  This replicates my request @ https://github.com/svg/svgo/issues/1300_

**Comment by RazrFalcon** [comment]
I think svgcleaner already does all of this. Do you have any specific examples?

**Comment by TPS** [comment]
Let's take https://github.com/edent/SuperTinyIcons/blob/master/images/guidelines/guideline.svg
```SVG
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Guidelines" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%"
fill="#222"/><circle fill="#f43" r="256" cx="256" cy="256"/><circle fill="#fd0" r="217.5" cx="256" cy="256"/><circle fill="#5d6" r="192" cx="256" cy="256"/></svg>
```
which is cleaned to
```SVG
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><rect fill="#222" height="512" rx="15%" width="512"/><circle cx="256" cy="256" fill="#f43" r="256"/><circle cx="256" cy="256" fill="#fd0" r="217.5"/><circle cx="256" cy="256" fill="#5d6" r="192"/></svg>
```
but could be
```SVG
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><rect
fill="#222" height="512"
rx="15%"
width="512"/><circle cx="256" cy="256" fill="#f43" r="256"/><circle cx="256" cy="256"
fill="#fd0" r="217.5"/><circle cx="256" cy="256" fill="#5d6" r="192"/></svg>
```
for the same number of bytes.  (I agree not best example, but gets the point across.)  This last would be visually simpler (& be more able to be understood _what change_ when commiting here on GitHub).

**Comment by JoKalliauer** [comment]
@TPS maybe try ` --indent 1` see [Documentaion](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc#set-xml-nodes-indent) ?
```svg
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
 <rect fill="#222" height="512" rx="15%" width="512"/>
 <circle cx="256" cy="256" fill="#f43" r="256"/>
 <circle cx="256" cy="256" fill="#fd0" r="217.5"/>
 <circle cx="256" cy="256" fill="#5d6" r="192"/>
</svg>

```

[My last svg](https://gitlab.com/inkscape/inbox/uploads/c8a625cf0502a24f3f01043deeec79ac/guidelinecCc.svg) is imho visually simpler (& be more able to be understood what change when commiting here on GitHub).

**Comment by RazrFalcon** [comment]
@TPS It's impossible to implement.
