### ISSUE TITLE
Wikimedia Compatibility Settings

### ISSUE THREAD

**Issue by TPS** [RazrFalcon/svgcleaner#223]
@RazrFalcon It'd be amazing to have a toggle to allow only optimizations that are compatible with [Wikimedia's very old SVG rasterizer](https://commons.m.wikimedia.org/wiki/Help:SVG#librsvg). (The [Commons SVG Checker](https://commons.m.wikimedia.org/wiki/Commons:Commons_SVG_Checker) should be specifically helpful.)

_N.B.: This replicates my request @ https://github.com/jakearchibald/svgomg/issues/195_

**Comment by RazrFalcon** [comment]
This is out of scope and already possible anyway.

**Comment by TPS** [comment]
How's it possible?  I didn't see an option for this.

I agree it might be out-of-scope, but it _would_ be an amazing feature.

**Comment by JoKalliauer** [comment]
@TPS: Some features are implemented such as  `--join-arcto-flags no` for [https://phabricator.wikimedia.org/T217990
](https://phabricator.wikimedia.org/T217990), or `--list-separator comma` for [https://phabricator.wikimedia.org/T32033](https://phabricator.wikimedia.org/T32033)

More recommended svgcleaner-options for commons.wikimedia can be found at [https://commons.wikimedia.org/wiki/User:JoKalliauer/Optimization#svgcleaner](https://commons.wikimedia.org/wiki/User:JoKalliauer/Optimization#svgcleaner)

If you want to bugfix for wikimedia-files you can use [https://svgworkaroundbot.toolforge.org/ ](https://svgworkaroundbot.toolforge.org/ )(using [https://github.com/JoKalliauer/cleanupSVG](https://github.com/JoKalliauer/cleanupSVG) )

However the bugs of librsvg are "endless", it is imho even implossible to render all svg's correctly.
Wikimedia uses an outdated version of librsvg, many problems are already fixed, see [https://phabricator.wikimedia.org/T193352](https://phabricator.wikimedia.org/T193352) for Details.

PS On Wikimedia there is a very slow discussion if the renderer should be changed [https://phabricator.wikimedia.org/T40010](https://phabricator.wikimedia.org/T40010), the most promising results are by [https://github.com/RazrFalcon/resvg](https://github.com/RazrFalcon/resvg) by @RazrFalcon , see [https://phabricator.wikimedia.org/T243893](https://phabricator.wikimedia.org/T243893) for Details.

**Comment by RazrFalcon** [comment]
@TPS You have to simply know `librsvg` bugs. And I don't plan adding any library-specific presets or something.
