### ISSUE TITLE
Remove spaces after large-arc and sweep flags

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/svgcleaner#227]
Spec: https://www.w3.org/TR/SVG11/paths.html#PathDataBNF

```
d="M300 200 h-150 a150 150 0 1 0 150 -150 z"
```

To:

```
d="M300 200 h-150 a150 150 0 10150 -150 z"
```

Currently only supported in modern browsers, many design software does not support it, and should be disabled by default.

Svgo: https://github.com/svg/svgo/commit/258fecfa6b4a037d98ad2614f5c9573728f6959d

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc#join-arcto-flags ?

**Comment by yisibl** [comment]
Awesome!
