### ISSUE TITLE
Add separate option to remove title element

### ISSUE THREAD

**Issue by mdio** [RazrFalcon/SVGCleaner#23]
Right now the title element is included in the option "Remove invisible elements" which also handles desc, script and others.

Depending on the context, the title element is not exactly invisible, as it is for example used in browsers ([Firefox](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title#Browser_compatibility), [Chrome/Safari/Opera](https://bugs.webkit.org/show_bug.cgi?id=16854)) to display a tooltip.

For me it would be very useful to
- exclude title element from "Remove invisible elements"
- add separate option "Remove title element" which does as it says when checked

btw, thanks for this useful piece of software. :)

**Comment by RazrFalcon** [comment]
Thanks. I didn't know about this feature.
I'll add this option in next release.

**Comment by mdio** [comment]
Thank you for the fast response!
I'm looking forward to it.

**Comment by RazrFalcon** [comment]
Implemented.
