### ISSUE TITLE
Multiple text coordinates being removed incorrectly.

### ISSUE THREAD

**Issue by citroboy** [RazrFalcon/SVGCleaner#24]
It is common in charts to specify the axis labels in one text or tspan element with multiple coordinates to spread the characters across the axis. eg.

&lt;text x="0 10 20 30 40" y="0"&gt;01234&lt;/text&gt;

SVGCleaner is removing the extra coordinates like so:

&lt;text x="0" y="0"&gt;01234&lt;/text&gt;

this has the undesirable effect of scrunching the labels together.
It is permissible for both coordinates to be multiple.

While I am here I'd like to add my voice to those who said that squeezing every last byte out is not the only reason to use SVGCleaner. I want SVG I can edit by hand. These goals are not contradictory, well crafted SVG will almost always be smaller than machine generated.

**Comment by RazrFalcon** [comment]
Yes, it's a bug.

I'm not fully understand last sentence, but yes, cleaning by hands always better. SVG Cleaner are still in development, that's why most of the features are not implemented yet. Also, you can't clean file by hands in 10 ms =)

**Comment by citroboy** [comment]
I just mean you should think about human editability as well as size when designing optimizations. There are some options I prefer to leave out for this reason, eg. --color-to-rrggbb and --convert-basic-shapes
In fact I would like to have opposites of these options, and maybe a humanize preset. I have several more feature requests if you need ideas :-)

**Comment by RazrFalcon** [comment]
What exactly do you mean by "human editability/readability"? New, still, developed version already support saving colors as names. XML structure can be saved with newlines/indent. Shapes, probably, can be even reconverted from paths.

I plan to make next version(s) more like svg processor, not only cleaner.

Any ideas are always welcome.

**Comment by citroboy** [comment]
Well, humans being what they are, there are things like taste and subjectivity involved so I can't really say 'exactly'. But when writing SVG I tend to prefer color names, basic shapes, meaningful IDs, individual transforms rather than matrices, if I don't need a tspan I just use text, bezier curves rather than long paths, maximum use of defs and grouping to minimize repetition, relative coordinates wherever possible, css for text styling, regularly spaced elements might become a pattern...
Some of this you already have covered. Some probably cannot be automated. If you can look at the output of SVGCleaner and render each element in your head then you're getting there.

Another very useful feature would be to crop the page to the drawing and add a user-definable margin. I have not found any program that will do this on the command line without exploding text into glyphs.

I'm not sure if this would be generally useful, or widely supported, but in theory it would be possible to analyse a set of SVG files and extract congruent elements into a separate defs file.

**Comment by RazrFalcon** [comment]
I see. Problem is, that it will increase file size, and not decrease, for what tool is designed.

Detecting "meaningful IDs" are imposible. Only by some kind of patterns.
Transform "explaining" will blow file size.
Other stuff are already supported.

Cropping page to drawing also didn't change file size, so it's not svg cleaner job.

It's probably better to implement all of this in separate project, like svg-humanize, and after I finish my svg processing library it will be easy to implement, so stay tune, maybe in 2016 I'll finally finish new version of svg cleaner.

**Comment by RazrFalcon** [comment]
Fixed.
