### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by kpcyrd** [RazrFalcon/svgcleaner#243]
hello!

The last release is from 2018, more than 3 years ago and a lot changed! The currently latest release didn't contain a lock-file for example, which causes the Arch Linux package to be unreproducible. A Cargo.lock file has been commited in the meantime, so the package would likely become reproducible with a new release.

Thanks!

**Comment by RazrFalcon** [comment]
Duplicate of #243

**Comment by RazrFalcon** [comment]
Duplicate of #157

**Comment by kpcyrd** [comment]
hmm, I think #157 is solved and could be closed, this issue is about tagging a new release. :)

**Comment by RazrFalcon** [comment]
I'm not making a new release on purpose. The project is abandoned. I just don't have time working on it. And no, adding a tag is not enough for a release.
