### ISSUE TITLE
numbers without separators

### ISSUE THREAD

**Issue by AbiSo** [RazrFalcon/SVGCleaner#32]
When svgcleaner re-computes coordinates and writes them back it does not place white-spaces or seperators like comma. For example in various cases I got following result after svgcleaner-cli "cleaned" SVGs created with InkScape:
`<path id="polygon5" d="... -3.498l35.916 ..."/>`

The problem is that these two values could be mis-interpreted. That would increase robustness. In my case I used librsvg with cairo-backend. The resulting image had _infinite_ long lines. 

Better would be to write
`-3.498l35 0.916`
or
`-3.498l35 .916`

Now I got correct results.

**Comment by RazrFalcon** [comment]
Hello.

Just uncheck "Remove unneeded symbols in 'd' attribute" in Paths tab.
