### ISSUE TITLE
Build error under Arch Linux 64 bit,  git head

### ISSUE THREAD

**Issue by stefanhusmann** [RazrFalcon/svgcleaner#33]
This is what I get:

   Compiling svgcleaner v0.6.92 (file:///home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner)
     Running `rustc src/lib.rs --crate-name svgcleaner --crate-type lib -C opt-level=3 --out-dir /home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release --emit=dep-info,link -L dependency=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release -L dependency=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release/deps --extern svgdom=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release/deps/libsvgdom-a1497506a80f39da.rlib --extern clap=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release/deps/libclap-315a0a334d3f6b4c.rlib`
error: file not found for module `rm_invalid_stops`
  --> src/task/mod.rs:64:5
   |
64 | mod rm_invalid_stops;
   |     ^^^^^^^^^^^^^^^^
   |
   = help: name the file either rm_invalid_stops.rs or rm_invalid_stops/mod.rs inside the directory "src/task"

error: aborting due to previous error

error: Could not compile `svgcleaner`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name svgcleaner --crate-type lib -C opt-level=3 --out-dir /home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release --emit=dep-info,link -L dependency=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release -L dependency=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release/deps --extern svgdom=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release/deps/libsvgdom-a1497506a80f39da.rlib --extern clap=/home/haawda/paketierung/meine_Pakete/svgcleaner-git/src/SVGCleaner/target/release/deps/libclap-315a0a334d3f6b4c.rlib` (exit code: 101)

**Comment by RazrFalcon** [comment]
Thanks. I forgot to add new files to the git.
