### ISSUE TITLE
Minify SVG

### ISSUE THREAD

**Issue by martinjlowm** [RazrFalcon/svgcleaner#35]
Just stumbled across this project and I like the idea!

I am starting to only provide SVG graphics for websites I design (because why not!) and excess spaces, tabs and newlines etc. are extra bytes to transfer. Do you plan to provide a "minify" feature similar to what exists for JS and CSS?

I apologise if it's already implemented. I haven't looked at the source just yet.

**Comment by RazrFalcon** [comment]
Hello.

Just open a file cleaned with default options and you will get your answer.

**Comment by martinjlowm** [comment]
That is slick! Let me just close this :)
