### ISSUE TITLE
Installable through cargo install?

### ISSUE THREAD

**Issue by ctjhoa** [RazrFalcon/svgcleaner#54]
Hi,
Is `svgcleaner` installable through `cargo install` command?
It's not specified in the README.

**Comment by RazrFalcon** [comment]
Installable where? cargo will install it into cargo folder.

Also, svgcleaner isn't in the creates, if you asking about this. So probably no.

**Comment by ctjhoa** [comment]
> Installable where?

`$CARGO_HOME` is set to `$HOME/.cargo` by default. I think it's pretty common to install rust stuff through `cargo` like `npm` does it for node. You just need to include `$CARGO_HOME` in your `PATH`. For example [ripgrep](https://github.com/BurntSushi/ripgrep#installation) support cargo install.

> Also, svgcleaner isn't in the creates

You mean [crates.io](https://crates.io/)?

**Comment by RazrFalcon** [comment]
> You mean crates.io?

Yes...

Ok. I will add svgcleaner to the crates.

**Comment by RazrFalcon** [comment]
Done.
