### ISSUE TITLE
Clippy warnings

### ISSUE THREAD

**Issue by brashaw** [RazrFalcon/svgcleaner#61]
Just a heads up: ran [clippy](https://github.com/Manishearth/rust-clippy) on the latest build and got quite a few warnings.

I would fix them myself but it seems like you'd want to ignore some of them (like `collapsible_if` in a few places).

**Comment by RazrFalcon** [comment]
Hello. Yes, I ran clippy from time to time. And yes, I ignore **collapsible_if** and **cyclomatic_complexity**. First one makes lines too long. I can't fit into 100 symbols.

**Comment by brashaw** [comment]
Throw some `#[allow()]`s in there. :)

Great project btw. I get a ~30% reduction on most of my SVGs.
