### ISSUE TITLE
Option to disable style to XML attribute conversion

### ISSUE THREAD

**Issue by palob** [RazrFalcon/svgcleaner#62]
As far as I can see there is no option to disable the style to XML attribute conversion.

This however breaks gradient stop colour editability.

Snippet from original file:

```
   <stop style="stop-color:#e4e4e4;stop-opacity:1"/>
   <stop offset="1" style="stop-color:#eee;stop-opacity:1"/>
```

Snippet from cleaned file, gradient can be edited in Inkscape but when the file is rendered outside the changed colour isn't rendered by some SVG engines.

```
   <stop offset="0" stop-color="#e4e4e4" stop-opacity="1"/>
   <stop offset="1" stop-color="#eee" stop-opacity="1"/>
```

QtSVG (5.7.0), librsvg(2.40.16) still show the original stop colours.
Gecko, WebKit and Chromium show the newly set colours correctly.

**Comment by RazrFalcon** [comment]
No. You can't. It's architecture decision in libsvgdom. It can't be optional.

I don't understand your examples. They are correct. Can you provide complete example as an SVG file?

**Comment by palob** [comment]
My question is whether there is an option which preserves what I showed in the first snippet, i.e. have presentational attributes joined as one ``style`` attribute.

Prior to ``0.6.90`` this could be done via ``--join-style-atts``.

However for the new ``[--join-style-attributes](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.rst#join-presentational-attributes)`` option now there's a minum of 5 seperate attributes before this is done.

In my example it's only 2 seperate attribute I need to have joined to prevent the bug.

**Comment by RazrFalcon** [comment]
Currently, there is no such option.

Moreover, I still can't understand the problem with splitting a style attribute. It's completely valid by SVG spec.

The `--join-style-attributes` works only with 5 or more attributes because smaller amount doesn't make SVG file smaller.

**Comment by palob** [comment]
That's true. However when you edit such gradient in Inkscape (editing a stop colour) the new stop colour doesn't override nor deletes the ``stop-colour`` attribute but saves the new colour as a new ``style`` attribute.

This additional ambiguous ``style`` attribute is neglected by QtSVG and librsvg.

Well, basically that is an Inkscape bug.

**Comment by RazrFalcon** [comment]
It's actually both since QtSvg, and probably librsvg, doesn't support correct style processing order.

For now - you should write about this bug to Inkscape. Just for case. It probably wouldn't be fixed soon. 

Converting all presentation attributes into `style` is not a current priority, since it will increase file size. Which is bad. 

I will think about it, but for now - use svgcleaner only before publishing and not during editing process.

**Comment by palob** [comment]
Thanks for your time. I found out I can fix this by just running ``svgcleaner`` again after editing.

I'm going to report it anyway.

**Comment by RazrFalcon** [comment]
You can join all style attributes with `--join-style-attributes=all` now.

**Comment by palob** [comment]
Thanks muchly :+1:
