### ISSUE TITLE
same-class style properties overwrite previous definitions

### ISSUE THREAD

**Issue by gmarinov** [RazrFalcon/svgcleaner#63]
e.g. this will not get parsed correctly:

```
<style>
  .cls-1,.cls-17{fill:yellow;}
  .cls-1{stroke:red;}
  .cls-17{stroke:black;}
</style>
```

expected: cls-1 has stroke:red, fill:yellow; cls-17 has stroke:black, fill:yellow
actual: both cls-1 and cls-17 class elements lose their fill.

changing to the following "works":

```
.cls-1{stroke:red;fill:yellow;}
.cls-17{stroke:black;fill:yellow;}
```

**Comment by RazrFalcon** [comment]
Yep. That's a bug.

**Comment by gmarinov** [comment]
this simplified example is based on actual export from Adobe CC

**Comment by RazrFalcon** [comment]
Fixed: https://github.com/RazrFalcon/libsvgdom/commit/6ee7cc2f81ba5a7b6526baff8beed1d8fc613f55

I can build exe for you. Just say what OS do you use. Or you can build it from source.

**Comment by gmarinov** [comment]
@RazrFalcon wow, cool. I use OSX.

**Comment by RazrFalcon** [comment]
Here it is. Put it into `SVG Cleaner.app/Contents/MacOS`.

[svgcleaner-cli.zip](https://github.com/RazrFalcon/svgcleaner/files/560890/svgcleaner-cli.zip)

**Comment by gmarinov** [comment]
confirmed working! thank you so much.

**Comment by RazrFalcon** [comment]
Thank you for bug reporting.
