### ISSUE TITLE
Keep classes for symbolic icons

### ISSUE THREAD

**Issue by lexeii** [RazrFalcon/svgcleaner#64]
Hi Evgeniy,

GNOME symbolic icons are have predefined classes that can not be removed: `warning`, `error`, and `success` ([more info](https://github.com/GNOME/gnome-icon-theme-symbolic)).

Currently these classes are stripped with the message like:
`Warning: Could resolve unknown class: error.`

**Comment by RazrFalcon** [comment]
Hello.

Currently, any external dependency cannot be resolved and preserved.

The main goal, as mentioned in the readme, is to clean files created in vector editors. svgcleaner is useless for handwritten files. More specifically - svgcleaner is designed for static, self-contained files.

I think it can't be implemented, since you have to manually list all styles that should be saved.

**Comment by lexeii** [comment]
I used svgcleaner to shrink svg files for the great [Paper](https://github.com/snwh/paper-icon-theme) icon theme (I maintain some packages for the SliTaz Linux). Results are very good, svg becomes 60-90% smaller. Log is [here](http://cook.slitaz.org/cooker.cgi?pkg=paper-icon-theme) if you're interested, search the word "class" on the page.

Other GTK+3 compatible icon themes contains these classes as well.

I see only one solution for me now: to inject definition for these three classes into svg, then use svgcleaner, and then remove the styles.

**Comment by RazrFalcon** [comment]
So you basically need an option called: keep unresolved classes? It can be done, but I can't guarantee that elements, which use this classes, would not be removed. Is this fine for you?

**Comment by lexeii** [comment]
Yes, it would be great.

**Comment by RazrFalcon** [comment]
Hello.

Try this: [svgcleaner.zip](https://github.com/RazrFalcon/svgcleaner/files/568076/svgcleaner.zip)

Usage:
`svgcleaner --remove-unresolved-classes=false in.svg out.svg`

PS: no GUI for now

**Comment by lexeii** [comment]
Hi Evgeniy,

Thank you for binary; sorry I use 32 bit OS and compiled svgcleaner on my own.

Brief tests have shown that everything is working as it was intended.
Thank you for the fast reply. Keep up the good work!
