### ISSUE TITLE
How to override "Cleaned file is bigger than original ..."

### ISSUE THREAD

**Issue by mikebronner** [RazrFalcon/svgcleaner#66]
Is there a way to force SVG Cleaner to process the file, even if the file size is smaller before cleaning? The reason being that SVG Cleaner also cleans up and fixes some issues that are inherent when exporting SVGs from different programs. SVG Cleaner lets me "baseline" the different images to a common format.

**Comment by RazrFalcon** [comment]
Hello. You can do this using CLI (`--copy-on-error=true`), but GUI doesn't have such option.
Should be added probably.

**Comment by mikebronner** [comment]
Thanks! :)

**Comment by mikebronner** [comment]
Tried running it, but got this error: 

```
/Applications/SVG\ Cleaner.app/Contents/MacOS/svgcleaner-cli Charge.svg Charge_cleaned.svg --remove-unreferenced-ids=false --trim-ids=false --trim-paths=false --indent=4 copy-on-error=true
Error: Found argument 'copy-on-error=true' which wasn't expected, or isn't valid in this context

USAGE:
    svgcleaner-cli <in-file> <out-file> --trim-ids <FLAG> --remove-unreferenced-ids <FLAG> --indent <INDENT> --trim-paths <FLAG>

For more information try --help
```

**Comment by shawnlauzon** [comment]
The option named has changed: it's now `--allow-bigger-file`
