### ISSUE TITLE
Reduce Decimal Precision

### ISSUE THREAD

**Issue by mikebronner** [RazrFalcon/svgcleaner#69]
Is there a command line option to reduce or remove decimal precision in paths or other elements?

**Comment by RazrFalcon** [comment]
1) https://github.com/RazrFalcon/svgcleaner/blob/master/FAQ.md#can-you-add-an-option-to-specify-a-numeric-precision
2) https://github.com/RazrFalcon/svgcleaner/commit/2672e693df583b644e1d168334de9d04d70935d1
3) https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.rst#set-path-s-coordinates-numeric-precision

**Comment by mikebronner** [comment]
Perfect, thank you! :) Happy new year!
