### ISSUE TITLE
Feature Request: Remove Empty Attributes

### ISSUE THREAD

**Issue by mikebronner** [RazrFalcon/svgcleaner#70]
It might be useful to provide an option that strips empty attributes that have no effect on rendering?

**Comment by RazrFalcon** [comment]
What kind of empty attributes? Empty attributes is not parsed already.

**Comment by mikebronner** [comment]
Sorry I haven't replied sooner ... I have been trying to see where it occurred but haven't been able to reproduce it. Wondering now if I supplied a bad command-line argument that prevent that file from running at all. Will close for now and re-open if I find it occurring again. My apologies. :)
