### ISSUE TITLE
Remove overflow property where it has no effect

### ISSUE THREAD

**Issue by slyrz** [RazrFalcon/svgcleaner#73]
Right now svgcleaner keeps [overflow properties](https://www.w3.org/TR/SVG/masking.html#OverflowProperty) in the SVG files untouched. They can be removed for all elements that don't establish new viewports.

[Scour](https://github.com/scour-project/scour) removes the overflow-property [like this.](https://github.com/scour-project/scour/blob/25549b35d30c3c4d96c4cf817dff0c242bc362ba/scour/scour.py#L1563-L1579) The first if-case is probably the most effective one. At least I have SVGs where Inkscape added unnecessary `overflow:visible` styles to all my path elements.

**Comment by RazrFalcon** [comment]
Yeap, it's not implemented yet, because, as you can see in the spec, the definition of the `overflow` is pretty big. Lots of edge cases.

**Comment by slyrz** [comment]
Yes, and frankly, I think it's futile to implement anything of that spec besides the first bullet point. Too much work for little reward. I can't test it at the moment, but I think Inkscape adds the CSS style `overflow:visible` to all shapes and paths by default. Removing these would be a big win. I can make a PR if you want.

**Comment by RazrFalcon** [comment]
Well, removing only `overflow:visible` is easy. I wanted to implement the `overflow` completely. I'll look into it.

Thanks for PR, but problem not in implementation, but in testing. I bet that something will went wrong.

**Comment by slyrz** [comment]
Okay then, I didn't know you had the removal of the overflow property planned already. I just noticed it today after I tried to clean some Inkscape files and thought I should open an issue. For me this isn't a high priority issue, as a simple `sed 's/overflow:visible;//g'` helps me to get rid of the property without breaking my SVGs.

**Comment by RazrFalcon** [comment]
Well, simple regex will not work in a wild. =) 

Yes, there are lots of ideas. You can also grep sources for TODO. But still any ideas are welcome.

**Comment by RazrFalcon** [comment]
Done. Check it out.

**Comment by slyrz** [comment]
Works great, all the overflows are gone!

**Comment by RazrFalcon** [comment]
Great.
