### ISSUE TITLE
No way to read SVG from stdin and write to stdout

### ISSUE THREAD

**Issue by Wallacoloo** [RazrFalcon/svgcleaner#85]
It's not uncommon to want to use this tool in a pipeline (e.g. `build-svg | svgcleaner | gzip > output.svgz`), but this isn't supported today.

In theory, the existing CLI *should* allow for this:
```
$ build-svg | svgcleaner /dev/stdin /dev/stdout | gzip > output.svgz
```

Instead, an error is produced:
```
Error: Invalid value for '<in-file>': The file format must be SVG.
```

This is because the input extension is verified against ".svg". This can be worked around:
```
$ ln -s /dev/stdin stdin.svg
$ ln -s /dev/stdout stdout.svg
$ build-svg | svgcleaner stdin.svg stdout.svg| gzip > output.svgz
```

But this workaround is hardly ergonomic. I think this can be reasonably improved by either whitelisting `/dev/stdin` and `/dev/stdout`, allowing input/output arguments that don't have a "svg" extension, or using `-` to represent stdio (e.g. `svgcleaner - -` reads and writes to stdio, `scgcleaner - output.svg` reads from stdin and writes to `output.svg`. I've seen this convention used in a few pieces of software).

**Comment by RazrFalcon** [comment]
Why not using:
```
build-svg | svgcleaner -c - | gzip > output.svgz
```

This should work.

**Comment by Wallacoloo** [comment]
@RazrFalcon Oh, my bad! I was using an older version of svgcleaner that didn't have a `-c` option. I should have built the git version first :/
