### ISSUE TITLE
Error: Failed to resolved attribute "overflow"

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/svgcleaner#88]
i got error as in title. Inkscape can open this file without problems.
Using v0.9.0 on Windows
[OperatingPlan.zip](https://github.com/RazrFalcon/svgcleaner/files/1074452/OperatingPlan.zip)

P.S. Typo: should be "failed to **resolve** attribute..."

**Comment by RazrFalcon** [comment]
Should be replaced with a warning I guess.

What application do you use to produce this file?

**Comment by Vasilich** [comment]
> What application do you use to produce this file?
No idea - it is not my file, i've taken it from 
https://github.com/vvvv/SVG/blob/master/Tests/Svg.UnitTests/Resources/Issue212_MakerEnd/OperatingPlan.svg

**Comment by RazrFalcon** [comment]
Fixed by: https://github.com/RazrFalcon/libsvgdom/commit/fd428970c7397c74d52bf84c7427e6fc43b10ca3
