### ISSUE TITLE
Error: Invalid transform

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/svgcleaner#89]
I got this error:
Error: Invalid transform at 7:81
tried to disable applying transforms to anything - still fails.
Inkscape has no problems with it, and even opened in Inkscape and saved as new SVG, cleaner shows same error (just on different position).

[BoundsTest.zip](https://github.com/RazrFalcon/svgcleaner/files/1074473/BoundsTest.zip)

**Comment by RazrFalcon** [comment]
I don't support commas between transforms. But looks like I should.

Will fix it soon.

**Comment by RazrFalcon** [comment]
Fixed by: https://github.com/RazrFalcon/libsvgparser/commit/43c89a01b3c029c8b7142510c2d247721362c096
