### ISSUE TITLE
Remove unresolved classes seems to have no effect

### ISSUE THREAD

**Issue by slyrz** [RazrFalcon/svgcleaner#90]
I'm running *svgcleaner* (version 0.9.1) and discovered some confusing behavior when it comes to keeping class names.

The flag `--remove-unresolved-classes=no` seems to have no effect. Take this file as input:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path class="bar" d="m0 0h100v100h-100z" fill="#f00"/>
</svg>
```

With `--remove-unresolved-classes=no` it still removes the class:  

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="m0 0h100v100h-100z" fill="#f00"/>
</svg>
```

Only with `--remove-unresolved-classes=no --remove-nonsvg-attributes=no` it keeps the class:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path class="bar" d="m0 0h100v100h-100z" fill="#f00"/>
</svg>
```

**Comment by RazrFalcon** [comment]
Does it the same issue: https://github.com/RazrFalcon/svgcleaner/issues/76 ?

**Comment by slyrz** [comment]
You're right, this issue accidentally covered some other parts. Sorry about that, I edited my comment and removed the group from the examples to avoid confusion. 

Take a look at the updated comment. This is what I think is some unexpected behaviour by the command line flags.

**Comment by RazrFalcon** [comment]
Well... It's literally a copy-paste error: https://github.com/RazrFalcon/svgcleaner/blob/6013f9871df55ad9196644d3dd6defae034c472a/src/cli.rs#L424..L425

The `RemoveNonsvgAttributes` mentioned twice and `RemoveUnresolvedClasses` doesn't used at all.

**Comment by RazrFalcon** [comment]
Fixed: https://github.com/RazrFalcon/svgcleaner/commit/d77489a1a7a35a5f775327fa5d0336d2b721b363

You can build svgcleaner from master or I can make a build for you (if you tell me your OS). I don't what to make a whole new release only with such small fixes...

**Comment by slyrz** [comment]
Thank you! Glad to hear it was a simple fix. Just ran the master version and it works as expected.
