### ISSUE TITLE
Processing &apos;

### ISSUE THREAD

**Issue by lexeii** [RazrFalcon/svgcleaner#92]
Hi,
I found that `&apos;` presence in the style definition leads to an error.
`&apos;` looks completely valid (but rarely met) here.

- https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/actions/address-book-new-symbolic.svg
```
Warning: Style attribute '-inkscape-font-specification:Sans' is skipped.
Warning: Style attribute '-inkscape-font-specification:&apos' is skipped.
Error: Expected ':', found 'B' at pos 37:2768.
```
- https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/actions/call-stop-symbolic.svg
```
Warning: Style attribute '-inkscape-font-specification:&apos' is skipped.
Error: Expected ':', found 'V' at pos 33:651.
```
- https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/places/folder-download-symbolic.svg
```
Warning: Style attribute '-inkscape-font-specification:&apos' is skipped.
Error: Expected ':', found 'M' at pos 28:713.
```
Used `svgcleaner 0.9.1` compiled on 32-bit Linux system with `rust 1.19.0`.
Used options:
```
--copy-on-error
--quiet
--multipass
--remove-unresolved-classes no
--apply-transform-to-paths yes
--coordinates-precision 1
--paths-coordinates-precision 1
```

**Comment by RazrFalcon** [comment]
Yes. That's a bug.

**Comment by RazrFalcon** [comment]
Fixed by: https://github.com/RazrFalcon/libsvgparser/commit/b208ef10cfdb95c6ec2e6ab35d97a0de15226fce

**Comment by RazrFalcon** [comment]
Just run:
```
cargo install --force svgcleaner
```
