### ISSUE TITLE
prebuilt issue

### ISSUE THREAD

**Issue by bydbest** [RazrFalcon/svgcleaner#99]
I clicked on prebuilt package and it is linked to GUI release.i wanted to install in centos so svgcleaner release package https://github.com/RazrFalcon/svgcleaner/archive/v0.9.1.tar.gz is sufficient or i have to install rust first ??

**Comment by RazrFalcon** [comment]
No. It should be completely portable.

**Comment by bydbest** [comment]
this is ok  then wget https://github.com/RazrFalcon/svgcleaner/archive/v0.9.1.tar.gz
 tar xzf v0.9.1.tar.gz
 cd svgcleaner
 make
 sudo make install

**Comment by RazrFalcon** [comment]
Oh, no, it's just a source code. You need this: https://github.com/RazrFalcon/svgcleaner-gui/releases/download/v0.9.1/svgcleaner_linux_x86_64_0.9.1.tar.gz

**Comment by bydbest** [comment]
thanks. rust is not required right ?? i can directly go with this  ??
 wget https://github.com/RazrFalcon/svgcleaner-gui/releases/download/v0.9.1/svgcleaner_linux_x86_64_0.9.1.tar.gz
tar xzf v0.9.1.tar.gz
cd svgcleaner
make
sudo make install

**Comment by RazrFalcon** [comment]
No. All you have to do is extract the archive and double click the `svgcleaner-gui`.

**Comment by bydbest** [comment]
running from command using exec command

**Comment by RazrFalcon** [comment]
For cli use just `svgcleaner`. There are two executables there.

**Comment by bydbest** [comment]
svgcleaner: command not found
 as i could not run make install as it is getting extracted in root. should i download and untar and keep all files in one svgcleaner folder and then try to make and install ??

**Comment by RazrFalcon** [comment]
1. There is nothing to install. It's portable.
1. If you need to run a local file - use `./svgcleaner`. It's a bash basics.

**Comment by bydbest** [comment]
oh sorry. its working, great. i missed.thanks

**Comment by derhuerst** [comment]
@RazrFalcon how do I get Windows CLI binaries?

**Comment by RazrFalcon** [comment]
@derhuerst you should install Windows revision and get `svgcleaner-cli.exe` from there. There are no separated CLI builds for now.

**Comment by derhuerst** [comment]
Well, i want to use `svgcleaner` in an npm module. Therefore, installation is not an option for me.

see https://github.com/derhuerst/svgcleaner-static#svgcleaner-static

**Comment by RazrFalcon** [comment]
I've planed to add `win32.zip`, `linux_x86_64.tar.gz` and `macos.zip` in the next release. Is it what you want?

Also, I can add builds for the latest tag (0.9.1) too.

**Comment by derhuerst** [comment]
Yup, that would be great!

**Comment by RazrFalcon** [comment]
@derhuerst done.
